package com.kingplus.social;

import android.app.Activity;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.Query;

import java.util.ArrayList;
import java.util.List;

public class KingGiftCenterActivity extends Activity {
    private static final int BG=0xff171420,CARD=0xff2a2636,GOLD=0xffffdf19,MUTED=0xffaaa2b5;
    private final String[] names={"Rose","Heart","Crown","Star Castle","Royal Car","Galaxy","Golden Dragon","King Throne","Love Rain","Party Rocket","Diamond Crown","Universe"};
    private final String[] icons={"🌹","💗","👑","⭐","🏎","🌌","🐉","🪑","💞","🚀","💎","🪐"};
    private final int[] costs={50,200,1000,3000,5000,10000,19800,36000,68000,120000,168000,520000};
    private final int[] vip={0,0,1,2,3,5,8,12,18,25,35,45};
    private FirebaseFirestore db; private FirebaseUser me; private String targetUid="",targetName="User";private LinearLayout body,history;private TextView balance;
    private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private GradientDrawable bg(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;} private TextView tv(String s,int z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(b)t.setTypeface(null,Typeface.BOLD);t.setPadding(dp(12),dp(5),dp(12),dp(5));t.setGravity(Gravity.CENTER_VERTICAL);return t;} private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    @Override public void onCreate(Bundle b){super.onCreate(b);targetUid=getIntent().getStringExtra("targetUid");targetName=getIntent().getStringExtra("targetName");if(targetUid==null)targetUid="";if(targetName==null||targetName.trim().isEmpty())targetName="User";try{db=FirebaseFirestore.getInstance();me=FirebaseAuth.getInstance().getCurrentUser();}catch(Exception ignored){}render();refreshBalance();loadHistory();}
    private void render(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=tv("‹",38,Color.WHITE,false);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(50),dp(56)));TextView title=tv("Gift Center",20,Color.WHITE,true);head.addView(title,new LinearLayout.LayoutParams(0,dp(56),1));balance=tv("💎 --",13,GOLD,true);balance.setGravity(Gravity.CENTER);head.addView(balance,new LinearLayout.LayoutParams(dp(110),dp(44)));root.addView(head);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(8),dp(14),dp(30));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);TextView hero=tv("🎁 Send a gift to "+targetName+"\nVIP unlocks • secure wallet transaction • realtime history",17,Color.WHITE,true);hero.setBackground(bg(0xff332d46,18));body.addView(hero,new LinearLayout.LayoutParams(-1,dp(90)));drawCatalog();TextView hh=tv("GIFT HISTORY",12,MUTED,true);body.addView(hh,new LinearLayout.LayoutParams(-1,dp(42)));history=new LinearLayout(this);history.setOrientation(LinearLayout.VERTICAL);body.addView(history);}
    private void drawCatalog(){LevelSystem.Snapshot s=LevelSystem.read(this);for(int i=0;i<names.length;i++){final int k=i;LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(dp(10),dp(5),dp(8),dp(5));r.setBackground(bg(CARD,14));TextView icon=tv(icons[i],28,Color.WHITE,false);icon.setGravity(Gravity.CENTER);r.addView(icon,new LinearLayout.LayoutParams(dp(54),dp(62)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(tv(names[i],15,Color.WHITE,true),new LinearLayout.LayoutParams(-1,dp(31)));tx.addView(tv("💎 "+costs[i]+"   •   "+(vip[i]==0?"Open":"VIP "+vip[i]),11,s.vipLevel>=vip[i]?0xffc9c3d2:0xffff8f8f,false),new LinearLayout.LayoutParams(-1,dp(24)));r.addView(tx,new LinearLayout.LayoutParams(0,dp(62),1));TextView send=tv(s.vipLevel>=vip[i]?"Send ›":"🔒",13,s.vipLevel>=vip[i]?GOLD:MUTED,true);send.setGravity(Gravity.CENTER);r.addView(send,new LinearLayout.LayoutParams(dp(70),dp(62)));r.setOnClickListener(v->{if(LevelSystem.read(this).vipLevel<vip[k]){toast("Unlocks at VIP "+vip[k]);return;}quantity(k);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(66));lp.setMargins(0,dp(4),0,dp(4));body.addView(r,lp);}}
    private void quantity(int k){String[] q={"1","9","49","99"};new android.app.AlertDialog.Builder(this).setTitle(icons[k]+" "+names[k]+" • quantity").setItems(q,(d,w)->{int n=Integer.parseInt(q[w]);long total=(long)costs[k]*n;if(total>50000000L){toast("Choose a smaller quantity");return;}send(k,n,(int)total);}).setNegativeButton("Cancel",null).show();}
    private void send(int k,int qty,int total){if(me==null){int local=getSharedPreferences("PartyActivity",MODE_PRIVATE).getInt("coins",100000);if(local<total){toast("Not enough TEST coins");return;}getSharedPreferences("PartyActivity",MODE_PRIVATE).edit().putInt("coins",local-total).apply();LevelSystem.gift(this,total);toast(icons[k]+" "+names[k]+" x"+qty+" sent in TEST mode");refreshBalance();return;}if(targetUid.isEmpty()||targetUid.equals(me.getUid())){toast("Choose another user");return;}CloudBackend.sendGift(targetUid,names[k]+" x"+qty,total,(ok,msg)->runOnUiThread(()->{toast(msg);if(ok){LevelSystem.gift(this,total);refreshBalance();loadHistory();}}));}
    private void refreshBalance(){if(me==null||db==null){int c=getSharedPreferences("PartyActivity",MODE_PRIVATE).getInt("coins",100000);balance.setText("💎 "+c+" TEST");return;}db.collection("wallets").document(me.getUid()).get().addOnSuccessListener(d->{Long c=d.getLong("coins");balance.setText("💎 "+(c==null?0:c));}).addOnFailureListener(e->balance.setText("💎 --"));}
    private void loadHistory(){if(history==null)return;history.removeAllViews();if(me==null||db==null){history.addView(tv("Sign in to view secure sent/received gift history",13,MUTED,false));return;}List<DocumentSnapshot> all=new ArrayList<>();final int[] done={0};java.util.function.Consumer<List<DocumentSnapshot>> add=list->{all.addAll(list);done[0]++;if(done[0]==2)renderHistory(all);};db.collection("wallet_ledger").whereEqualTo("senderUid",me.getUid()).limit(30).get().addOnSuccessListener(q->add.accept(q.getDocuments())).addOnFailureListener(e->add.accept(new ArrayList<>()));db.collection("wallet_ledger").whereEqualTo("targetUid",me.getUid()).limit(30).get().addOnSuccessListener(q->add.accept(q.getDocuments())).addOnFailureListener(e->add.accept(new ArrayList<>()));}
    private void renderHistory(List<DocumentSnapshot> rows){history.removeAllViews();java.util.Collections.sort(rows,(a,b)->{com.google.firebase.Timestamp ta=a.getTimestamp("createdAt"),tb=b.getTimestamp("createdAt");long aa=ta==null?0:ta.toDate().getTime(),bb=tb==null?0:tb.toDate().getTime();return Long.compare(bb,aa);});int shown=0;for(DocumentSnapshot d:rows){String s=d.getString("senderUid"),t=d.getString("targetUid");if(!targetUid.isEmpty()&&!targetUid.equals(s)&&!targetUid.equals(t))continue;String g=d.getString("giftName");Long c=d.getLong("cost");boolean sent=me.getUid().equals(s);TextView r=tv((sent?"↗ Sent ":"↙ Received ")+(g==null?"Gift":g)+"  •  💎"+(c==null?0:c),13,Color.WHITE,true);r.setBackground(bg(CARD,12));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(48));lp.setMargins(0,dp(3),0,dp(3));history.addView(r,lp);if(++shown>=20)break;}if(shown==0)history.addView(tv("No gift history with this user yet",13,MUTED,false));}
}
