from pathlib import Path

p = Path('/tmp/mbdd-src/app/src/main/java/com/example/diamonddiary/MainActivity.java')
s = p.read_text()

s = s.replace('    private Button loginButton;\n    private TextView loginStatus;\n', '''    private Button loginButton;\n    private Button bossLoginButton;\n    private Button hourLoginButton;\n    private Button diamondLoginButton;\n    private TextView loginStatus;\n    private String pendingLoginRole;\n    private String pendingLoginMode;\n''')

old = '''    private void createLoginScreen(FrameLayout root) {\n        login = baseScreen();\n        TextView title = titleText("◆  MB ડાયમંડ ડાયરી");\n        login.addView(title, fullWrap());\n\n        TextView subtitle = bodyText("તમારા Google એકાઉન્ટથી લોગીન કરો");\n        subtitle.setGravity(Gravity.CENTER);\n        subtitle.setPadding(0, dp(18), 0, dp(18));\n        login.addView(subtitle, fullWrap());\n\n        loginButton = primaryButton("Google સાથે લોગીન કરો");\n        loginButton.setOnClickListener(v -> signIn());\n        login.addView(loginButton, fullWrap());\n\n        loginStatus = bodyText("");\n        loginStatus.setGravity(Gravity.CENTER);\n        loginStatus.setPadding(0, dp(12), 0, 0);\n        login.addView(loginStatus, fullWrap());\n        root.addView(login, new FrameLayout.LayoutParams(-1, -1));\n    }\n'''

new = '''    private void createLoginScreen(FrameLayout root) {\n        login = baseScreen();\n        TextView title = titleText("◆  MB ડાયમંડ ડાયરી");\n        login.addView(title, fullWrap());\n\n        TextView subtitle = bodyText("પહેલા તમારો પ્રકાર પસંદ કરો, પછી Google એકાઉન્ટથી લોગીન કરો");\n        subtitle.setGravity(Gravity.CENTER);\n        subtitle.setPadding(0, dp(18), 0, dp(14));\n        login.addView(subtitle, fullWrap());\n\n        TextView bossTitle = sectionText("શેઠ");\n        bossTitle.setGravity(Gravity.CENTER);\n        bossTitle.setPadding(0, 0, 0, dp(8));\n        login.addView(bossTitle, fullWrap());\n        bossLoginButton = primaryButton("શેઠ તરીકે Google સાથે લોગીન કરો");\n        bossLoginButton.setOnClickListener(v -> beginRoleLogin("boss", "both"));\n        login.addView(bossLoginButton, fullWrap());\n\n        TextView workerTitle = sectionText("કારીગર — તમારું કામ પસંદ કરો");\n        workerTitle.setGravity(Gravity.CENTER);\n        workerTitle.setPadding(0, dp(18), 0, dp(8));\n        login.addView(workerTitle, fullWrap());\n\n        hourLoginButton = secondaryButton("ઓફિસ / કલાકનું કામ");\n        hourLoginButton.setOnClickListener(v -> beginRoleLogin("worker", "hour"));\n        login.addView(hourLoginButton, fullWrap());\n\n        diamondLoginButton = secondaryButton("હીરાનું કામ");\n        diamondLoginButton.setOnClickListener(v -> beginRoleLogin("worker", "diamond"));\n        login.addView(diamondLoginButton, fullWrap());\n\n        loginButton = bossLoginButton;\n        loginStatus = bodyText("");\n        loginStatus.setGravity(Gravity.CENTER);\n        loginStatus.setPadding(0, dp(12), 0, 0);\n        login.addView(loginStatus, fullWrap());\n        root.addView(login, new FrameLayout.LayoutParams(-1, -1));\n    }\n\n    private void beginRoleLogin(String role, String mode) {\n        pendingLoginRole = role;\n        pendingLoginMode = mode;\n        signIn();\n    }\n\n    private void setLoginButtonsEnabled(boolean enabled) {\n        if (bossLoginButton != null) bossLoginButton.setEnabled(enabled);\n        if (hourLoginButton != null) hourLoginButton.setEnabled(enabled);\n        if (diamondLoginButton != null) diamondLoginButton.setEnabled(enabled);\n    }\n'''

if old not in s:
    raise SystemExit('login block not found')
s = s.replace(old, new)
s = s.replace('        loginButton.setEnabled(false);\n', '        setLoginButtonsEnabled(false);\n')
s = s.replace('                                loginButton.setEnabled(true);\n                                if (task.isSuccessful()) showAuthState();\n', '''                                setLoginButtonsEnabled(true);\n                                if (task.isSuccessful()) applyPendingRoleAfterLogin();\n''')
s = s.replace('        loginButton.setEnabled(true);\n        loginStatus.setText(message);\n', '''        setLoginButtonsEnabled(true);\n        loginStatus.setText(message);\n''')

needle = '    private void signInError(String message) {\n'
insert = '''    private void applyPendingRoleAfterLogin() {\n        FirebaseUser user = auth.getCurrentUser();\n        if (user == null) {\n            showAuthState();\n            return;\n        }\n        String selectedRole = pendingLoginRole;\n        String selectedMode = pendingLoginMode;\n        pendingLoginRole = null;\n        pendingLoginMode = null;\n        if (!("boss".equals(selectedRole) || "worker".equals(selectedRole))) {\n            showAuthState();\n            return;\n        }\n        database.collection("users").document(user.getUid()).get()\n            .addOnSuccessListener(snapshot -> {\n                String savedRole = safe(snapshot.getString("role"));\n                if ("boss".equals(savedRole) || "worker".equals(savedRole)) {\n                    showAuthState();\n                    return;\n                }\n                saveRole(selectedRole, selectedMode);\n            })\n            .addOnFailureListener(e -> saveRole(selectedRole, selectedMode));\n    }\n\n'''
s = s.replace(needle, insert + needle, 1)
s = s.replace('            currentRole = null;\n            currentMode = null;\n', '            currentRole = null;\n            currentMode = null;\n            pendingLoginRole = null;\n            pendingLoginMode = null;\n', 1)
p.write_text(s)
