package com.kingplus.social;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.media.MediaPlayer;
import android.media.MediaRecorder;
import android.os.Bundle;
import android.os.CountDownTimer;
import android.view.Gravity;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.ListenerRegistration;
import com.google.firebase.firestore.Query;
import com.google.firebase.firestore.SetOptions;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Original KING Plus ecosystem expansion.
 * Adds deeper KTV, PK, Family, Rank, Gift and Arcade flows without copying third-party assets/code.
 */
public class KingEcosystemProActivity extends Activity {
    private static final int BG=0xff120920, CARD=0xff281744, CARD2=0xff37205d, PURPLE=0xff8a49ed,
            GOLD=0xffffd768, MUTED=0xffc7b9d8, RED=0xffd64661, BLUE=0xff4687ff;
    private static final int REQ_AUDIO=880;

    private FirebaseFirestore db; private FirebaseUser me; private LinearLayout body; private TextView pageTitle;
    private String route="home", roomId="", roomName="KING Party", familyCode="", displayName="KING User";
    private final List<ListenerRegistration> listeners=new ArrayList<>();
    private MediaRecorder recorder; private MediaPlayer player; private File recording; private boolean recordingNow=false;
    private CountDownTimer pkTimer;

    private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    private GradientDrawable bg(int c,int r){GradientDrawable d=new GradientDrawable();d.setColor(c);d.setCornerRadius(dp(r));return d;}
    private TextView tv(String s,int z,int c,boolean b){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(b)t.setTypeface(null,Typeface.BOLD);t.setPadding(dp(12),dp(7),dp(12),dp(7));return t;}
    private String safe(String s,String f){return s==null||s.trim().isEmpty()?f:s.trim();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    private boolean cloud(){if(me==null||db==null){toast("Google / Firebase sign-in required");return false;}return true;}
    private boolean room(){if(!cloud())return false;if(roomId.isEmpty()){toast("Open this feature from a live Party Room");return false;}return true;}

    @Override public void onCreate(Bundle b){super.onCreate(b);try{db=FirebaseFirestore.getInstance();me=FirebaseAuth.getInstance().getCurrentUser();}catch(Exception ignored){}if(me!=null&&me.getDisplayName()!=null)displayName=safe(me.getDisplayName(),displayName);route=safe(getIntent().getStringExtra("route"),"home");roomId=safe(getIntent().getStringExtra("roomId"),"");roomName=safe(getIntent().getStringExtra("roomName"),"KING Party");shell();show(route);}

    private void shell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(8),dp(8),dp(8),0);TextView back=tv("‹",38,Color.WHITE,true);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(52),dp(56)));pageTitle=tv("KING Ecosystem",20,Color.WHITE,true);head.addView(pageTitle,new LinearLayout.LayoutParams(0,dp(56),1));root.addView(head);
        HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout tabs=new LinearLayout(this);tabs.setPadding(dp(8),0,dp(8),dp(8));String[][] a={{"🎤","KTV","ktv"},{"⚔️","PK","pk"},{"👑","Family","family"},{"🏆","Rank","rank"},{"🎁","Gift","gift"},{"🎮","Arcade","arcade"}};for(String[] x:a){TextView t=tv(x[0]+" "+x[1],12,Color.WHITE,true);t.setGravity(Gravity.CENTER);t.setBackground(bg(CARD2,16));String r=x[2];t.setOnClickListener(v->show(r));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(102),dp(42));lp.setMargins(dp(4),0,dp(4),0);tabs.addView(t,lp);}hs.addView(tabs);root.addView(hs,new LinearLayout.LayoutParams(-1,dp(52)));
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(14),dp(10),dp(14),dp(32));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}

    private void clearListeners(){for(ListenerRegistration r:listeners)try{r.remove();}catch(Exception ignored){}listeners.clear();if(pkTimer!=null){pkTimer.cancel();pkTimer=null;}}
    private void show(String r){clearListeners();route=r;body.removeAllViews();pageTitle.setText(title(r));if("ktv".equals(r))ktv();else if("pk".equals(r))pk();else if("family".equals(r))family();else if("rank".equals(r))rank("level");else if("gift".equals(r))gift();else if("arcade".equals(r))arcade();else home();}
    private String title(String r){if("ktv".equals(r))return "KTV Studio";if("pk".equals(r))return "PK Arena Pro";if("family".equals(r))return "Family Pro";if("rank".equals(r))return "Rank Center";if("gift".equals(r))return "Gift Universe";if("arcade".equals(r))return "KING Arcade";return "KING Ecosystem";}
    private void hero(String a,String b){TextView h=tv(a+"\n"+b,17,Color.WHITE,true);h.setBackground(bg(CARD,18));h.setPadding(dp(16),dp(14),dp(16),dp(14));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(10));body.addView(h,lp);}
    private TextView button(String s,Runnable r){TextView t=tv(s,14,Color.WHITE,true);t.setGravity(Gravity.CENTER);t.setBackground(bg(PURPLE,14));t.setOnClickListener(v->r.run());return t;}
    private void row(String icon,String a,String b,Runnable r){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(dp(10),dp(5),dp(10),dp(5));x.setBackground(bg(CARD,15));TextView ic=tv(icon,27,Color.WHITE,false);ic.setGravity(Gravity.CENTER);x.addView(ic,new LinearLayout.LayoutParams(dp(52),dp(62)));LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);TextView aa=tv(a,15,Color.WHITE,true);aa.setPadding(0,0,0,0);TextView bb=tv(b,11,MUTED,false);bb.setPadding(0,dp(2),0,0);info.addView(aa);info.addView(bb);x.addView(info,new LinearLayout.LayoutParams(0,dp(62),1));TextView ar=tv("›",27,GOLD,true);ar.setGravity(Gravity.CENTER);x.addView(ar,new LinearLayout.LayoutParams(dp(34),dp(62)));x.setOnClickListener(v->r.run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(72));lp.setMargins(0,dp(4),0,dp(4));body.addView(x,lp);}
    private void section(String s){TextView t=tv(s.toUpperCase(Locale.US),12,MUTED,true);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(38));lp.setMargins(0,dp(8),0,0);body.addView(t,lp);}

    private void home(){hero("✨ KING Plus Ecosystem Pro","Deeper KTV, PK, Family, Rank, Gift and Arcade flows with original KING Plus UI and realtime state.");row("🎤","KTV Studio","Shared queue, singer stage, local voice recording",()->show("ktv"));row("⚔️","PK Arena Pro","Realtime teams, timed battle, gift score, result card",()->show("pk"));row("👑","Family Pro","Treasury points, family level, activities, family call",()->show("family"));row("🏆","Rank Center","Level, VIP, game, chat and event rankings",()->show("rank"));row("🎁","Gift Universe","Secure gifts, wall, wishes, lucky effects",()->show("gift"));row("🎮","KING Arcade","Local games + realtime Party Room games",()->show("arcade"));}

    private void ktv(){hero("🎤 KTV Studio • "+roomName,roomId.isEmpty()?"Open from Party Room for realtime stage":"Realtime queue + singer stage + local rehearsal recorder");LinearLayout actions=new LinearLayout(this);actions.addView(button("＋ Request song",this::requestSong),new LinearLayout.LayoutParams(0,dp(48),1));TextView rec=button(recordingNow?"■ Stop recording":"● Record voice",this::toggleRecording);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(48),1);rp.setMargins(dp(8),0,0,0);actions.addView(rec,rp);body.addView(actions);if(recording!=null&&recording.exists()){TextView play=button("▶ Play last recording",this::playRecording);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(46));pp.setMargins(0,dp(8),0,0);body.addView(play,pp);}section("Singer stage");LinearLayout stage=new LinearLayout(this);stage.setOrientation(LinearLayout.VERTICAL);stage.setPadding(dp(14),dp(12),dp(14),dp(12));stage.setBackground(bg(0xff173c67,18));TextView now=tv("🎙 Waiting for singer",18,GOLD,true);TextView meta=tv("Host/co-host can start a queued song",12,Color.WHITE,false);stage.addView(now);stage.addView(meta);body.addView(stage,new LinearLayout.LayoutParams(-1,dp(94)));section("Search / queue");EditText search=new EditText(this);search.setHint("Search requested songs…");search.setSingleLine(true);search.setTextColor(Color.WHITE);search.setHintTextColor(MUTED);search.setBackground(bg(CARD,14));body.addView(search,new LinearLayout.LayoutParams(-1,dp(48)));LinearLayout queue=new LinearLayout(this);queue.setOrientation(LinearLayout.VERTICAL);body.addView(queue);if(!room())return;DocumentReference state=db.collection("live_rooms").document(roomId).collection("room_settings").document("ktv");listeners.add(state.addSnapshotListener((d,e)->{if(e!=null||d==null)return;String song=safe(d.getString("song"),"Waiting for singer"),singer=safe(d.getString("singerName"),"—"),phase=safe(d.getString("phase"),"idle");now.setText("🎙 "+song);meta.setText("Singer: "+singer+" • "+phase);if("playing".equals(phase)){Long started=d.getLong("startedAtMs"),duration=d.getLong("durationSec");if(started!=null&&duration!=null){long left=Math.max(0,duration-(System.currentTimeMillis()-started)/1000L);meta.setText("Singer: "+singer+" • "+left+"s remaining");}}}));loadKtvQueue(queue,search.getText().toString());search.setOnEditorActionListener((v,a,event)->{loadKtvQueue(queue,search.getText().toString());return true;});TextView refresh=button("↻ Refresh queue",()->loadKtvQueue(queue,search.getText().toString()));LinearLayout.LayoutParams rr=new LinearLayout.LayoutParams(-1,dp(46));rr.setMargins(0,dp(8),0,0);body.addView(refresh,rr);}
    private void loadKtvQueue(LinearLayout queue,String filter){queue.removeAllViews();if(!room())return;db.collection("live_rooms").document(roomId).collection("events").orderBy("createdAt",Query.Direction.DESCENDING).limit(120).get().addOnSuccessListener(q->{List<DocumentSnapshot>rows=new ArrayList<>();for(DocumentSnapshot d:q.getDocuments())if("ktv_request".equals(d.getString("type")))rows.add(d);Collections.reverse(rows);String f=safe(filter,"").toLowerCase(Locale.US);int shown=0;for(DocumentSnapshot d:rows){String song=safe(d.getString("songName"),"Song"),who=safe(d.getString("actorName"),"User");if(!f.isEmpty()&&!song.toLowerCase(Locale.US).contains(f)&&!who.toLowerCase(Locale.US).contains(f))continue;TextView r=tv("🎵 "+song+"\nRequested by "+who,14,Color.WHITE,true);r.setBackground(bg(CARD,14));r.setOnClickListener(v->startKtvSong(song,who));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(62));lp.setMargins(0,dp(3),0,dp(3));queue.addView(r,lp);if(++shown>=40)break;}if(shown==0)queue.addView(tv("No matching song requests yet.",13,MUTED,false));}).addOnFailureListener(e->queue.addView(tv("Queue unavailable right now.",13,MUTED,false)));}
    private void requestSong(){if(!room())return;EditText e=new EditText(this);e.setHint("Song title / artist");e.setSingleLine(true);new AlertDialog.Builder(this).setTitle("Request KTV song").setView(e).setPositiveButton("Request",(d,w)->{String s=e.getText().toString().trim();if(s.isEmpty())return;Map<String,Object>m=new HashMap<>();m.put("actorUid",me.getUid());m.put("actorName",displayName);m.put("type","ktv_request");m.put("songName",s);m.put("text",displayName+" requested 🎵 "+s);m.put("createdAt",FieldValue.serverTimestamp());db.collection("live_rooms").document(roomId).collection("events").add(m).addOnSuccessListener(v->{toast("Added to KTV queue");show("ktv");}).addOnFailureListener(x->toast("Request failed"));}).setNegativeButton("Cancel",null).show();}
    private void startKtvSong(String song,String singer){if(!room())return;String[] ops={"Start on stage • 90 sec","Start on stage • 180 sec","Request host action"};new AlertDialog.Builder(this).setTitle(song).setItems(ops,(d,w)->{if(w==2){toast("Host/co-host controls the shared stage");return;}long dur=w==0?90:180;Map<String,Object>m=new HashMap<>();m.put("song",song);m.put("singerName",singer);m.put("phase","playing");m.put("durationSec",dur);m.put("startedAtMs",System.currentTimeMillis());m.put("updatedAt",FieldValue.serverTimestamp());db.collection("live_rooms").document(roomId).collection("room_settings").document("ktv").set(m).addOnSuccessListener(v->toast("KTV stage started")).addOnFailureListener(e->toast("Host/co-host permission required"));}).show();}
    private void toggleRecording(){if(recordingNow){stopRecording();show("ktv");return;}if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_AUDIO);return;}startRecording();show("ktv");}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_AUDIO&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED){startRecording();show("ktv");}}
    private void startRecording(){try{File base=getExternalFilesDir(null);if(base==null)base=getFilesDir();File dir=new File(base,"ktv");if(!dir.exists())dir.mkdirs();recording=new File(dir,"ktv_rehearsal_"+System.currentTimeMillis()+".m4a");recorder=new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setAudioEncodingBitRate(128000);recorder.setAudioSamplingRate(44100);recorder.setOutputFile(recording.getAbsolutePath());recorder.prepare();recorder.start();recordingNow=true;toast("KTV rehearsal recording started");}catch(Exception e){recordingNow=false;toast("Recorder unavailable");try{if(recorder!=null)recorder.release();}catch(Exception ignored){}recorder=null;}}
    private void stopRecording(){if(!recordingNow)return;try{recorder.stop();toast("Recording saved in KING Plus app files");}catch(Exception e){toast("Recording could not be saved");}try{recorder.release();}catch(Exception ignored){}recorder=null;recordingNow=false;}
    private void playRecording(){if(recording==null||!recording.exists()){toast("No recording yet");return;}try{if(player!=null){player.release();player=null;}player=new MediaPlayer();player.setDataSource(recording.getAbsolutePath());player.prepare();player.start();toast("Playing rehearsal");}catch(Exception e){toast("Playback unavailable");}}

    private void pk(){hero("⚔️ PK Arena Pro • "+roomName,"Realtime Red vs Blue • timed round • gift-backed score • result card");if(!room())return;LinearLayout teams=new LinearLayout(this);TextView red=button("🔴 Join Red",()->joinPk("red"));red.setBackground(bg(RED,14));teams.addView(red,new LinearLayout.LayoutParams(0,dp(50),1));TextView blue=button("🔵 Join Blue",()->joinPk("blue"));blue.setBackground(bg(BLUE,14));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(50),1);bp.setMargins(dp(8),0,0,0);teams.addView(blue,bp);body.addView(teams);LinearLayout control=new LinearLayout(this);control.addView(button("⚡ Start 90s",()->setPkRound(true,90)),new LinearLayout.LayoutParams(0,dp(48),1));TextView end=button("■ End",()->setPkRound(false,0));LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(0,dp(48),1);ep.setMargins(dp(8),0,0,0);control.addView(end,ep);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(48));cp.setMargins(0,dp(8),0,dp(8));body.addView(control,cp);
        LinearLayout arena=new LinearLayout(this);arena.setGravity(Gravity.CENTER);TextView rs=tv("🔴 RED\n0",24,Color.WHITE,true);rs.setGravity(Gravity.CENTER);rs.setBackground(bg(0xff74233b,18));TextView mid=tv("VS\n90",17,GOLD,true);mid.setGravity(Gravity.CENTER);TextView bs=tv("🔵 BLUE\n0",24,Color.WHITE,true);bs.setGravity(Gravity.CENTER);bs.setBackground(bg(0xff214e91,18));arena.addView(rs,new LinearLayout.LayoutParams(0,dp(118),1));arena.addView(mid,new LinearLayout.LayoutParams(dp(78),dp(118)));arena.addView(bs,new LinearLayout.LayoutParams(0,dp(118),1));body.addView(arena);
        TextView result=tv("Waiting for PK round…",15,MUTED,true);result.setGravity(Gravity.CENTER);body.addView(result,new LinearLayout.LayoutParams(-1,dp(58)));DocumentReference state=db.collection("live_rooms").document(roomId).collection("room_settings").document("pk");listeners.add(state.addSnapshotListener((d,e)->{if(e!=null||d==null)return;boolean active=Boolean.TRUE.equals(d.getBoolean("active"));Long start=d.getLong("startedAtMs"),dur=d.getLong("durationSec");long duration=dur==null?90:dur;if(active&&start!=null)startPkTimer(mid,Math.max(0,duration*1000-(System.currentTimeMillis()-start)));else{if(pkTimer!=null){pkTimer.cancel();pkTimer=null;}mid.setText("VS\n0");}}));listeners.add(db.collection("live_rooms").document(roomId).collection("events").orderBy("createdAt",Query.Direction.DESCENDING).limit(300).addSnapshotListener((q,e)->{if(e!=null||q==null)return;Map<String,String>team=new LinkedHashMap<>();for(DocumentSnapshot d:q.getDocuments()){if("pk_join".equals(d.getString("type"))){String uid=d.getString("actorUid");if(uid!=null&&!team.containsKey(uid))team.put(uid,safe(d.getString("team"),""));}}long rScore=0,bScore=0;for(DocumentSnapshot d:q.getDocuments()){if(!"gift".equals(d.getString("type")))continue;Long v=d.getLong("giftValue");long val=v==null?0:Math.max(0,v);String t=team.get(d.getString("actorUid"));if("red".equals(t))rScore+=val;else if("blue".equals(t))bScore+=val;}rs.setText("🔴 RED\n"+rScore);bs.setText("🔵 BLUE\n"+bScore);String msg=rScore==bScore?"🤝 Draw":rScore>bScore?"🔥 Red team leads by "+(rScore-bScore):"❄️ Blue team leads by "+(bScore-rScore);result.setText(msg);}));
    }
    private void joinPk(String team){if(!room())return;Map<String,Object>m=new HashMap<>();m.put("actorUid",me.getUid());m.put("actorName",displayName);m.put("type","pk_join");m.put("team",team);m.put("text",displayName+" joined "+("red".equals(team)?"Red":"Blue")+" PK team");m.put("createdAt",FieldValue.serverTimestamp());db.collection("live_rooms").document(roomId).collection("events").add(m).addOnSuccessListener(v->toast("Joined "+team+" team")).addOnFailureListener(e->toast("Could not join team"));}
    private void setPkRound(boolean active,long sec){if(!room())return;Map<String,Object>m=new HashMap<>();m.put("active",active);m.put("durationSec",sec);m.put("startedAtMs",active?System.currentTimeMillis():0);m.put("startedBy",me.getUid());m.put("updatedAt",FieldValue.serverTimestamp());db.collection("live_rooms").document(roomId).collection("room_settings").document("pk").set(m,SetOptions.merge()).addOnSuccessListener(v->toast(active?"PK round started":"PK round ended")).addOnFailureListener(e->toast("Host/co-host permission required"));}
    private void startPkTimer(TextView mid,long ms){if(pkTimer!=null)pkTimer.cancel();if(ms<=0){mid.setText("VS\n0");return;}pkTimer=new CountDownTimer(ms,1000){public void onTick(long left){mid.setText("VS\n"+Math.max(0,left/1000));}public void onFinish(){mid.setText("VS\n0");}}.start();}

    private void family(){hero("👑 Family Pro","Family level • treasury points • activity • members • voice call");if(!cloud())return;db.collection("users").document(me.getUid()).get().addOnSuccessListener(u->{familyCode=safe(u.getString("familyCode"),"");if(familyCode.isEmpty()){row("➕","Create / Join Family","Open Family center to create or join",()->openCommunity("Family"));return;}loadFamily(familyCode);}).addOnFailureListener(e->row("👑","Open Family","Family data unavailable",()->openCommunity("Family")));}
    private void loadFamily(String code){DocumentReference f=db.collection("families").document(code);f.get().addOnSuccessListener(doc->{if(!doc.exists()){row("👑","Open Family","Family not found",()->openCommunity("Family"));return;}String familyName=safe(doc.getString("name"),"KING Family"),owner=safe(doc.getString("ownerUid"),"");TextView card=tv("👑 "+familyName+"\nCode: "+code,20,Color.WHITE,true);card.setBackground(bg(CARD2,18));body.addView(card,new LinearLayout.LayoutParams(-1,dp(82)));LinearLayout actions=new LinearLayout(this);actions.addView(button("💬 Family Chat",()->openCommunity("Family")),new LinearLayout.LayoutParams(0,dp(48),1));TextView call=button("🎙 Family Call",()->NativeMeetBridge.launch(this,"FAMILY-"+code,familyName+" Family Call",displayName,false));LinearLayout.LayoutParams clp=new LinearLayout.LayoutParams(0,dp(48),1);clp.setMargins(dp(8),0,0,0);actions.addView(call,clp);body.addView(actions);section("Family progress");TextView stats=tv("Loading family stats…",15,Color.WHITE,true);stats.setBackground(bg(CARD,14));body.addView(stats,new LinearLayout.LayoutParams(-1,dp(80)));final int[] members={0};final long[] treasury={0},activities={0};Runnable update=()->{int level=Math.max(1,Math.min(50,(int)(members[0]/2+treasury[0]/500+activities[0]/10+1)));stats.setText("Family Lv."+level+" / 50   •   👥 "+members[0]+" members\n🏦 Treasury "+treasury[0]+" points   •   🎯 Activities "+activities[0]);};f.collection("members").get().addOnSuccessListener(q->{members[0]=q.size();update.run();section("Members");for(DocumentSnapshot d:q.getDocuments())row("owner".equals(d.getString("role"))?"👑":"👤",safe(d.getString("name"),"User"),safe(d.getString("role"),"member"),()->{});});f.collection("treasury").limit(200).get().addOnSuccessListener(q->{long sum=0;for(DocumentSnapshot d:q.getDocuments()){Long a=d.getLong("amount");if(a!=null)sum+=Math.max(0,a);}treasury[0]=sum;update.run();});f.collection("activities").limit(200).get().addOnSuccessListener(q->{activities[0]=q.size();update.run();});section("Treasury & activity");LinearLayout ta=new LinearLayout(this);ta.addView(button("＋100 Family points",()->contributeFamily(code,100)),new LinearLayout.LayoutParams(0,dp(48),1));TextView check=button("✅ Daily check-in",()->familyActivity(code,"checkin"));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(48),1);xp.setMargins(dp(8),0,0,0);ta.addView(check,xp);body.addView(ta);row("📣","Family Activity Feed","Members can post safe activity events",()->familyActivity(code,"activity"));row("📤","Share Family Code","Invite friends using "+code,()->{Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,"Join my KING Plus Family "+familyName+" • Code "+code);startActivity(Intent.createChooser(i,"Share Family"));});if(owner.equals(me.getUid()))row("🛡","Owner controls","Manage members in Family center",()->openCommunity("Family"));});}
    private void contributeFamily(String code,long amount){Map<String,Object>m=new HashMap<>();m.put("uid",me.getUid());m.put("name",displayName);m.put("amount",amount);m.put("type","points");m.put("createdAt",FieldValue.serverTimestamp());db.collection("families").document(code).collection("treasury").add(m).addOnSuccessListener(v->{toast("Family treasury +"+amount+" points");show("family");}).addOnFailureListener(e->toast("Contribution unavailable"));}
    private void familyActivity(String code,String type){Map<String,Object>m=new HashMap<>();m.put("uid",me.getUid());m.put("name",displayName);m.put("type",type);m.put("text","checkin".equals(type)?displayName+" completed daily family check-in":displayName+" joined a Family activity");m.put("createdAt",FieldValue.serverTimestamp());db.collection("families").document(code).collection("activities").add(m).addOnSuccessListener(v->{toast("Family activity added");show("family");}).addOnFailureListener(e->toast("Activity unavailable"));}
    private void openCommunity(String tab){Intent i=new Intent(this,CommunityHubActivity.class);i.putExtra("tab",tab);startActivity(i);}

    private void rank(String type){route="rank";clearListeners();body.removeAllViews();hero("🏆 Rank Center","Real KING Plus public profiles and activity stats");LinearLayout tabs=new LinearLayout(this);String[][] x={{"Level","level"},{"VIP","vip"},{"Game","game"},{"Chat","chat"},{"Event","event"}};for(String[] a:x){TextView b=button(a[0],()->rank(a[1]));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(42),1);lp.setMargins(dp(2),0,dp(2),0);tabs.addView(b,lp);}body.addView(tabs);section(type+" ranking");if(!cloud())return;if("level".equals(type)||"vip".equals(type)){String field="level".equals(type)?"level":"vipLevel";db.collection("public_profiles").orderBy(field,Query.Direction.DESCENDING).limit(50).get().addOnSuccessListener(q->{int n=1;for(DocumentSnapshot d:q.getDocuments()){Long val=d.getLong(field);String nm=safe(d.getString("displayName"),"KING User");rankRow(n++,nm,field.equals("level")?"Lv."+(val==null?1:val):"VIP "+(val==null?0:val),safe(d.getString("uid"),d.getId()));}}).addOnFailureListener(e->body.addView(tv("Ranking unavailable until Firestore index/rules are ready.",13,MUTED,false)));}else{String field="game".equals(type)?"gameScore":"chat".equals(type)?"chatScore":"eventScore";db.collection("discover_stats").orderBy(field,Query.Direction.DESCENDING).limit(50).get().addOnSuccessListener(q->{int n=1;for(DocumentSnapshot d:q.getDocuments()){Long v=d.getLong(field);rankRow(n++,d.getId(),field+" "+(v==null?0:v),d.getId());}}).addOnFailureListener(e->body.addView(tv("Activity ranking unavailable right now.",13,MUTED,false)));}}
    private void rankRow(int n,String name,String score,String uid){String medal=n==1?"🥇":n==2?"🥈":n==3?"🥉":"#"+n;TextView r=tv(medal+"   "+name+"\n      "+score,14,Color.WHITE,true);r.setBackground(bg(CARD,14));r.setOnClickListener(v->{Intent i=new Intent(this,KingPublicProfileActivity.class);i.putExtra("uid",uid);i.putExtra("name",name);startActivity(i);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(58));lp.setMargins(0,dp(3),0,dp(3));body.addView(r,lp);}

    private void gift(){hero("🎁 Gift Universe","Secure wallet gifting + room gift wall + wishes + lucky effects");row("🎁","Full Gift Catalog","Open expanded KING Plus gift center",()->startActivity(new Intent(this,KingGiftCenterActivity.class)));row("🧱","Room Gift Wall","Summarize recent room gifts",this::giftWall);row("💫","Gift Wish","Choose a profile wish",this::giftWish);row("🍀","Lucky Gift","Free no-money visual lucky draw",this::luckyGift);row("🎒","Collection / Backpack","Daily free items and cosmetics",()->openCommunity("Collection"));}
    private void giftWall(){if(!room())return;body.removeAllViews();hero("🧱 Room Gift Wall",roomName);db.collection("live_rooms").document(roomId).collection("events").orderBy("createdAt",Query.Direction.DESCENDING).limit(150).get().addOnSuccessListener(q->{Map<String,Long> count=new LinkedHashMap<>();for(DocumentSnapshot d:q.getDocuments())if("gift".equals(d.getString("type"))){String g=safe(d.getString("giftName"),safe(d.getString("text"),"Gift"));count.put(g,count.getOrDefault(g,0L)+1);}if(count.isEmpty())body.addView(tv("No gifts yet.",13,MUTED,false));for(Map.Entry<String,Long> e:count.entrySet())row("🎁",e.getKey(),"×"+e.getValue(),()->{});});}
    private void giftWish(){String[] wishes={"Royal Castle","Galaxy Ship","Golden Tiger","Diamond Rain","KING Throne","Phoenix Flight","Moon Palace","Festival Crown"};new AlertDialog.Builder(this).setTitle("Choose Gift Wish").setItems(wishes,(d,w)->{getSharedPreferences("gift_wish",MODE_PRIVATE).edit().putString("wish",wishes[w]).apply();toast("Wish set: "+wishes[w]);}).show();}
    private void luckyGift(){String[] r={"🌹 Rose","⭐ Star","👑 Crown","🐯 Tiger","🚀 Rocket","🌌 Galaxy","💎 Diamond Rain","🎉 Festival"};String x=r[(int)(Math.random()*r.length)];new AlertDialog.Builder(this).setTitle("🍀 Lucky Gift").setMessage("You revealed\n\n"+x+"\n\nVisual/test reward only • no money or billing.").setPositiveButton("Nice",null).show();}

    private void arcade(){hero("🎮 KING Arcade","Playable games + realtime Party Room game entry");section("Board & skill");game("🎲","Online Ludo","ludo");game("⭕","Tic Tac Toe","tic_tac_toe");game("🧠","Memory","memory");game("🀄","Domino","domino");game("🎯","Bingo","bingo");section("Party deduction");game("🐺","Werewolf","werewolf");game("🕵","Spy","spy");game("🎨","Draw & Guess","draw");game("🐑","Sheep Fight","sheep");game("🦁","Crazy Zoo","zoo");section("Quick games");game("✊","Rock Paper Scissors","rps");game("🎲","Dice Duel","dice");game("🔢","Guess Number","guess");game("🪙","Coin Toss","coin");game("🎰","Lucky Slot","slot");game("⚡","Reaction Tap","reaction");game("🃏","High / Low","highlow");game("🎡","Lucky Wheel","wheel");row("👥","Realtime Party Room Games","Ready / start / shared result / rematch",()->{Intent i=new Intent(this,RoomGameActivity.class);i.putExtra("roomId",roomId);i.putExtra("roomName",roomName);startActivity(i);});}
    private void game(String icon,String name,String code){row(icon,name,"Play now",()->{Intent i=new Intent(this,GamePlayActivity.class);i.putExtra("game",code);startActivity(i);});}

    @Override protected void onDestroy(){clearListeners();stopRecording();try{if(player!=null)player.release();}catch(Exception ignored){}player=null;super.onDestroy();}
}