from pathlib import Path
import sys

root=Path(sys.argv[1])
pkg=root/'app/src/main/java/com/kingplus/social'

# -------- Main: real global level/VIP rankings + real Family entry --------
main=pkg/'MainActivity.java'
q=main.read_text()

old='''    private void rankingsPage(){
        screen="rankings"; base("Rankings","Real KING Plus activity only");
        text("👑 Live rankings",20,Color.WHITE,true);
        if(firebaseAuth==null || firebaseAuth.getCurrentUser()==null || firestore==null){
            text("Sign in to view real community and room activity. KING Plus no longer shows sample leaderboard names.",14,MUTED,false);
            button("Sign in",PURPLE,this::login);
            button("Back to Profile",CARD,this::profile);
            return;
        }
        text("Sample users and made-up charm/coin totals have been removed.",14,MUTED,false);
        text("Open Party to view the real Room Ranking, Gift Senders, Gift History and live room activity generated by signed-in members.",14,Color.WHITE,false);
        button("🎤 Open real Party rankings",PURPLE,this::openPartyActivity);
        button("👥 Open real Followers / Friends",CARD,()->startActivity(new Intent(this,SocialActivity.class)));
        button("Back to Profile",CARD,this::profile);
    }'''
new='''    private void rankingsPage(){
        screen="rankings"; base("Rankings","Real KING Plus profiles and activity");
        text("👑 Community Rankings",20,Color.WHITE,true);
        final com.google.firebase.auth.FirebaseUser rankUser943=currentSessionUser943();
        if(rankUser943==null||firestore==null){
            text("Sign in to view real KING Plus rankings.",14,MUTED,false);
            button("Sign in",PURPLE,this::login);button("Back to Profile",CARD,this::profile);return;
        }
        TextView state943=text("Loading real community rankings…",14,MUTED,false);
        firestore.collection("public_profiles").limit(80).get().addOnSuccessListener(snap->{
            if(isFinishing()||isDestroyed())return;
            java.util.List<com.google.firebase.firestore.DocumentSnapshot> profiles943=new java.util.ArrayList<>(snap.getDocuments());
            if(profiles943.isEmpty()){state943.setText("No ranked profiles yet. Rankings appear as real members build levels and VIP points.");return;}
            state943.setText("Verified from "+profiles943.size()+" public KING profiles");
            text("⭐ Level Ranking",17,Color.WHITE,true);
            profiles943.sort((a,b)->Long.compare(rankLevel943(b),rankLevel943(a)));
            int shown943=0;
            for(com.google.firebase.firestore.DocumentSnapshot d:profiles943){
                if(shown943>=10)break;
                addGlobalRankRow943(++shown943,d,"level");
            }
            text("💎 VIP Ranking",17,Color.WHITE,true);
            profiles943.sort((a,b)->Long.compare(rankVip943(b),rankVip943(a)));
            shown943=0;
            for(com.google.firebase.firestore.DocumentSnapshot d:profiles943){
                if(shown943>=10)break;
                addGlobalRankRow943(++shown943,d,"vip");
            }
        }).addOnFailureListener(e->{state943.setText("Rankings unavailable • tap Retry");button("↻ Retry Rankings",CARD,this::rankingsPage);});
        button("🎤 Room / Gift Rankings",PURPLE,this::openPartyActivity);
        button("👥 Followers / Friends",CARD,()->startActivity(new Intent(this,SocialActivity.class)));
        button("Back to Profile",CARD,this::profile);
    }
    private long rankLevel943(com.google.firebase.firestore.DocumentSnapshot d){Long v=d.getLong("level");return v==null?1L:Math.max(1L,v);}
    private long rankVip943(com.google.firebase.firestore.DocumentSnapshot d){Long v=d.getLong("vipLevel");return v==null?0L:Math.max(0L,v);}
    private void addGlobalRankRow943(int rank,com.google.firebase.firestore.DocumentSnapshot d,String mode){
        String uid=d.getString("uid");if(uid==null||uid.trim().isEmpty())uid=d.getId();
        String name=d.getString("displayName");if(name==null||name.trim().isEmpty())name="KING User";
        long lv=rankLevel943(d),vip=rankVip943(d);String medal=rank==1?"🥇":rank==2?"🥈":rank==3?"🥉":String.valueOf(rank);
        String metric="vip".equals(mode)?"VIP "+vip:"Lv."+lv;
        final String finalUid943=uid,finalName943=name;
        button(medal+"  "+name+"   •   "+metric,CARD,()->{Intent i=new Intent(this,KingPublicProfileActivity.class);i.putExtra("uid",finalUid943);i.putExtra("name",finalName943);startActivity(i);});
    }'''
if old not in q: raise SystemExit('rankingsPage marker missing')
q=q.replace(old,new,1)

old='''    private void familyAgencyPage(){
        screen="family_agency"; base("Family & Agency","Verified account data only");
        text("🏠 Family & Agency",24,Color.WHITE,true);
        text("The old device-only sample family members, fake host counts and fake active-room counts have been removed.",14,MUTED,false);
        if(firebaseAuth==null || firebaseAuth.getCurrentUser()==null || firestore==null){
            text("Sign in with Google/Firebase first. Family/agency membership will only be shown when it is backed by a real account record.",14,Color.WHITE,false);
            button("Sign in",PURPLE,this::login);
        } else {
            text("Signed in as: "+displayName,15,Color.WHITE,true);
            text("No verified Family/Agency record is available for this account yet.",14,MUTED,false);
            button("🎤 Open Party",PURPLE,this::openPartyActivity);
        }
        button("Back to Profile",CARD,this::profile);
    }'''
new='''    private void familyAgencyPage(){
        screen="family_agency"; base("Family & Agency","Real KING Family data");
        text("🏠 Family & Agency",24,Color.WHITE,true);
        final com.google.firebase.auth.FirebaseUser familyUser943=currentSessionUser943();
        if(familyUser943==null||firestore==null){text("Sign in to create or join a Family.",14,Color.WHITE,false);button("Sign in",PURPLE,this::login);button("Back to Profile",CARD,this::profile);return;}
        text("Signed in as: "+displayName,15,Color.WHITE,true);
        TextView familyState943=text("Checking Family membership…",14,MUTED,false);
        firestore.collection("users").document(familyUser943.getUid()).get().addOnSuccessListener(d->{
            String n=d.getString("familyName"),code=d.getString("familyCode");
            if(n!=null&&!n.trim().isEmpty())familyState943.setText("👑 "+n+(code==null||code.trim().isEmpty()?"":" • Code "+code));
            else familyState943.setText("No Family joined yet • open Family Center to create or join one.");
        }).addOnFailureListener(e->familyState943.setText("Family status unavailable • use Family Center to retry"));
        button("👑 Open Family Center",PURPLE,()->openCommunityHub700("Family"));
        button("🎤 Open Party",CARD,this::openPartyActivity);
        button("Back to Profile",CARD,this::profile);
    }'''
if old not in q: raise SystemExit('familyAgencyPage marker missing')
q=q.replace(old,new,1)

main.write_text(q)

# -------- CommunityHub: visible retry/empty states and visitor timestamp fix --------
hub=pkg/'CommunityHubActivity.java'
q=hub.read_text()

# People search failures -> visible retry action.
old='''.addOnSuccessListener(s->renderUsers(s.getDocuments())).addOnFailureListener(e->toast("Search unavailable"));return;}'''
new='''.addOnSuccessListener(s->renderUsers(s.getDocuments())).addOnFailureListener(e->communityRetry943("People search unavailable",()->searchPeople(raw)));return;}'''
if old not in q: raise SystemExit('public-id people search marker missing')
q=q.replace(old,new,1)
old='''z.get().addOnSuccessListener(s->renderUsers(s.getDocuments())).addOnFailureListener(e->toast("Search unavailable"));}'''
new='''z.get().addOnSuccessListener(s->renderUsers(s.getDocuments())).addOnFailureListener(e->communityRetry943("People search unavailable",()->searchPeople(raw)));}'''
if old not in q: raise SystemExit('people search marker missing')
q=q.replace(old,new,1)

# Room search had no failure UI.
old='''if(n==0)body.addView(tv("No matching live rooms.",14,MUTED,false));});}'''
new='''if(n==0)body.addView(tv("No matching live rooms.",14,MUTED,false));}).addOnFailureListener(e->communityRetry943("Room search unavailable",()->searchRooms(raw)));}'''
if old not in q: raise SystemExit('room search marker missing')
q=q.replace(old,new,1)

# Moments/post/topic failures.
q=q.replace('''.addOnFailureListener(x->toast("Could not post"));}''','''.addOnFailureListener(x->communityRetry943("Could not post Moment",()->postMoment(e)));}''',1)
q=q.replace(''').addOnFailureListener(e->toast("Moments unavailable"));''',''').addOnFailureListener(e->communityRetry943("Moments unavailable",()->render("Moments")));''',1)
q=q.replace(''').addOnFailureListener(e->body.addView(tv("Topic Square unavailable right now.",14,MUTED,false)));''',
            ''').addOnFailureListener(e->communityRetry943("Topic Square unavailable",()->render("Topics")));''',1)

# Family lookup should not silently pretend user has no family on network errors.
old='''    private void family(){body.addView(tv("Family & Agency",21,DARK,true));if(!cloud()){body.addView(tv("Sign in to use Family.",14,MUTED,false));return;}db.collection("users").document(me.getUid()).get().addOnSuccessListener(u->{String code=safe(u.getString("familyCode"),"");if(code.isEmpty()){familyJoinCreate();return;}db.collection("families").document(code).collection("members").document(me.getUid()).get().addOnSuccessListener(m->{if(m.exists())showFamily(code);else{clearFamily();familyJoinCreate();}}).addOnFailureListener(e->familyJoinCreate());}).addOnFailureListener(e->familyJoinCreate());}'''
new='''    private void family(){body.addView(tv("Family & Agency",21,DARK,true));if(!cloud()){body.addView(tv("Sign in to use Family.",14,MUTED,false));return;}TextView loading943=tv("Checking your Family…",13,MUTED,false);body.addView(loading943,new LinearLayout.LayoutParams(-1,dp(42)));db.collection("users").document(me.getUid()).get().addOnSuccessListener(u->{body.removeView(loading943);String code=safe(u.getString("familyCode"),"");if(code.isEmpty()){familyJoinCreate();return;}db.collection("families").document(code).collection("members").document(me.getUid()).get().addOnSuccessListener(m->{if(m.exists())showFamily(code);else{clearFamily();familyJoinCreate();}}).addOnFailureListener(e->communityRetry943("Could not verify Family membership",()->render("Family")));}).addOnFailureListener(e->{body.removeView(loading943);communityRetry943("Family unavailable",()->render("Family"));});}'''
if old not in q: raise SystemExit('family marker missing')
q=q.replace(old,new,1)

# Family create/join/save minimum failure feedback.
old='''r.collection("members").document(me.getUid()).set(mem).addOnSuccessListener(z->saveFamily(code,name));});});}'''
new='''r.collection("members").document(me.getUid()).set(mem).addOnSuccessListener(z->saveFamily(code,name)).addOnFailureListener(e->communityRetry943("Could not add Family owner",()->createFamily(name,0)));}).addOnFailureListener(e->communityRetry943("Could not create Family",()->createFamily(name,0)));}).addOnFailureListener(e->communityRetry943("Could not check Family code",()->createFamily(name,0)));}'''
if old not in q: raise SystemExit('createFamily tail marker missing')
q=q.replace(old,new,1)

old='''r.collection("members").document(me.getUid()).set(m).addOnSuccessListener(v->saveFamily(code,safe(f.getString("name"),"KING Family")));});}'''
new='''r.collection("members").document(me.getUid()).set(m).addOnSuccessListener(v->saveFamily(code,safe(f.getString("name"),"KING Family"))).addOnFailureListener(e->communityRetry943("Could not join Family",()->joinFamily(code)));}).addOnFailureListener(e->communityRetry943("Family lookup unavailable",()->joinFamily(code)));}'''
if old not in q: raise SystemExit('joinFamily tail marker missing')
q=q.replace(old,new,1)

old='''db.collection("users").document(me.getUid()).set(u,SetOptions.merge()).addOnSuccessListener(v->{getSharedPreferences("MainActivity",MODE_PRIVATE).edit().putString("family_code",code).putString("family_name",name).apply();render("Family");});}'''
new='''db.collection("users").document(me.getUid()).set(u,SetOptions.merge()).addOnSuccessListener(v->{getSharedPreferences("MainActivity",MODE_PRIVATE).edit().putString("family_code",code).putString("family_name",name).apply();render("Family");}).addOnFailureListener(e->communityRetry943("Could not save Family membership",()->saveFamily(code,name)));}'''
if old not in q: raise SystemExit('saveFamily tail marker missing')
q=q.replace(old,new,1)

# Family detail: visible members/chat empty/error states.
old='''r.collection("members").get().addOnSuccessListener(s->{for(DocumentSnapshot d:s.getDocuments()){'''
new='''r.collection("members").get().addOnSuccessListener(s->{if(s.isEmpty())body.addView(tv("No Family members found.",13,MUTED,false));for(DocumentSnapshot d:s.getDocuments()){'''
if old not in q: raise SystemExit('family members marker missing')
q=q.replace(old,new,1)
old='''if(owner.equals(me.getUid())&&!uid.equals(me.getUid()))x.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle(n).setMessage("Remove from Family?").setPositiveButton("Remove",(a,b)->r.collection("members").document(uid).delete().addOnSuccessListener(q->render("Family"))).setNegativeButton("Cancel",null).show();return true;});}});body.addView(tv("Family Chat",16,DARK,true));'''
new='''if(owner.equals(me.getUid())&&!uid.equals(me.getUid()))x.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle(n).setMessage("Remove from Family?").setPositiveButton("Remove",(a,b)->r.collection("members").document(uid).delete().addOnSuccessListener(q->render("Family"))).setNegativeButton("Cancel",null).show();return true;});}}).addOnFailureListener(e->communityRetry943("Family members unavailable",()->render("Family")));body.addView(tv("Family Chat",16,DARK,true));'''
if old not in q: raise SystemExit('family members tail marker missing')
q=q.replace(old,new,1)

old='''r.collection("messages").orderBy("createdAt",Query.Direction.DESCENDING).limit(30).get().addOnSuccessListener(s->{List<DocumentSnapshot>ds=new ArrayList<>(s.getDocuments());Collections.reverse(ds);for(DocumentSnapshot d:ds)chat.addView(tv(safe(d.getString("name"),"User")+": "+safe(d.getString("text"),""),13,DARK,false));});'''
new='''r.collection("messages").orderBy("createdAt",Query.Direction.DESCENDING).limit(30).get().addOnSuccessListener(s->{List<DocumentSnapshot>ds=new ArrayList<>(s.getDocuments());Collections.reverse(ds);if(ds.isEmpty())chat.addView(tv("No Family messages yet.",13,MUTED,false));for(DocumentSnapshot d:ds)chat.addView(tv(safe(d.getString("name"),"User")+": "+safe(d.getString("text"),""),13,DARK,false));}).addOnFailureListener(e->{chat.removeAllViews();TextView retry943=tv("Family chat unavailable • tap to retry",13,PURPLE,true);retry943.setOnClickListener(v->render("Family"));chat.addView(retry943);});'''
if old not in q: raise SystemExit('family messages marker missing')
q=q.replace(old,new,1)

# Lucky bag query failure gets a retry dialog.
q=q.replace(''').addOnFailureListener(e->toast("Lucky Bag unavailable"));''',
            ''').addOnFailureListener(e->KingUiState.error(this,"Lucky Bag unavailable",e.getLocalizedMessage(),()->familyLuckyBag940(code)));''',1)

# Relationships: both queries need visible error state.
old='''db.collection("relationships").whereEqualTo("uidB",me.getUid()).limit(30).get().addOnSuccessListener(b->{for(DocumentSnapshot d:b.getDocuments())if(seen.add(d.getId()))addRelationship(d);if(seen.isEmpty())body.addView(tv("No requests yet. Use Search to select a person.",13,MUTED,false));});});}'''
new='''db.collection("relationships").whereEqualTo("uidB",me.getUid()).limit(30).get().addOnSuccessListener(b->{for(DocumentSnapshot d:b.getDocuments())if(seen.add(d.getId()))addRelationship(d);if(seen.isEmpty())body.addView(tv("No requests yet. Use Search to select a person.",13,MUTED,false));}).addOnFailureListener(e->communityRetry943("Relationships unavailable",()->render("Relationship")));}).addOnFailureListener(e->communityRetry943("Relationships unavailable",()->render("Relationship")));}'''
if old not in q: raise SystemExit('relationships marker missing')
q=q.replace(old,new,1)

# Visitors bug: records are written with visitedAt; open profile and retry on failure.
q=q.replace('''.orderBy("updatedAt",Query.Direction.DESCENDING).limit(50).get()''',
            '''.orderBy("visitedAt",Query.Direction.DESCENDING).limit(50).get()''',1)
old='''row.setOnClickListener(v->openChat(uid,name));'''
new='''row.setOnClickListener(v->{Intent i=new Intent(this,KingPublicProfileActivity.class);i.putExtra("uid",uid);i.putExtra("name",name);startActivity(i);});'''
# Only replace first occurrence in visitors section by locating around visitors method.
vi=q.index('private void visitors750()')
rp=q.index(old,vi)
if rp<0: raise SystemExit('visitor row click marker missing')
q=q[:rp]+new+q[rp+len(old):]

old='''}).addOnFailureListener(e->body.addView(tv("Visitors unavailable right now.",14,MUTED,false)));'''
new='''}).addOnFailureListener(e->communityRetry943("Visitors unavailable",()->render("Visitors")));'''
if old not in q: raise SystemExit('visitors failure marker missing')
q=q.replace(old,new,1)

# Shared visible retry card.
marker='''    private void collection(){'''
helper='''    private void communityRetry943(String message,Runnable retry){
        TextView state943=tv("⚠ "+message+"\\n↻ Tap to retry",13,PURPLE,true);state943.setGravity(Gravity.CENTER);state943.setBackground(bg(0xfffff0f4,14));state943.setOnClickListener(v->KingSafe.run(this,"community-retry",retry));LinearLayout.LayoutParams lp943=new LinearLayout.LayoutParams(-1,dp(70));lp943.setMargins(0,dp(7),0,dp(7));body.addView(state943,lp943);
    }

'''
if marker not in q: raise SystemExit('collection marker missing for retry helper')
q=q.replace(marker,helper+marker,1)

hub.write_text(q)

# Version
gradle=root/'app/build.gradle'
g=gradle.read_text()
old="versionCode 142; versionName '9.4.3-session-social'"
if old not in g: raise SystemExit('v9.4.3 version marker missing')
gradle.write_text(g.replace(old,"versionCode 143; versionName '9.4.4-community-finalize'",1))

(root/'V9.4.4-WORKLOG.md').write_text('''# KING Plus v9.4.4 community/rank finalization

- adds real global Level and VIP leaderboards from public_profiles (no sample names/totals)
- Family & Agency duplicate page now reads real user family record and routes to real Family Center
- fixes Profile Visitors query field: visitedAt instead of updatedAt
- visitor rows open the real public profile
- People/Room search, Moments, Topics, Family, Relationships, Visitors and Lucky Bag gain visible retry states
- Family member and chat lists now show explicit empty/error states
- preserves no-billing behavior and all v9.4.3 session-safety fixes
''')
print('KING Plus v9.4.4 community finalization applied')
