package com.kingplus.social;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.ListenerRegistration;
import com.google.firebase.firestore.Query;
import java.util.HashMap;
import java.util.Map;

public class LiveCloudActivity extends Activity {
 private final int BG=0xff101426,CARD=0xff202744,PURPLE=0xff7146ec; private FirebaseFirestore db; private FirebaseUser user; private LinearLayout page; private ListenerRegistration roomsListener,messagesListener; private String openRoomId;
 @Override public void onCreate(Bundle s){super.onCreate(s);db=FirebaseFirestore.getInstance();user=FirebaseAuth.getInstance().getCurrentUser();if(user==null){new AlertDialog.Builder(this).setTitle("Firebase sign-in required").setMessage("Live rooms require a Firebase account.").setCancelable(false).setPositiveButton("Close",(d,w)->finish()).show();return;}renderRooms();}
 private int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);} private void base(String t,String s){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackgroundColor(BG);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(20),dp(28),dp(20),dp(36));sc.addView(page);setContentView(sc);label(t,27,Color.WHITE,true);if(s!=null)label(s,14,0xffc4bed8,false);} private TextView label(String v,int z,int c,boolean b){TextView t=new TextView(this);t.setText(v);t.setTextSize(z);t.setTextColor(c);if(b)t.setTypeface(null,android.graphics.Typeface.BOLD);t.setPadding(dp(4),dp(8),dp(4),dp(8));page.addView(t,new LinearLayout.LayoutParams(-1,-2));return t;} private Button button(String t,int c,View.OnClickListener l){Button b=new Button(this);b.setText(t);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackgroundColor(c);b.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,dp(5),0,dp(5));page.addView(b,p);return b;} private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextColor(Color.WHITE);e.setHintTextColor(0xffaca5c3);e.setSingleLine(true);e.setBackgroundColor(CARD);e.setPadding(dp(14),0,dp(14),0);page.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));return e;}
 private void clearListeners(){if(roomsListener!=null){roomsListener.remove();roomsListener=null;}if(messagesListener!=null){messagesListener.remove();messagesListener=null;}}
 private void renderRooms(){clearListeners();openRoomId=null;base("KING Plus Live","Real-time rooms + chat");label("Signed in: "+safeName(),14,0xffc4bed8,false);EditText rn=input("New live room name");button("＋ Create live room",PURPLE,v->{String n=rn.getText().toString().trim();if(n.length()<2){rn.setError("Enter room name");return;}Map<String,Object>r=new HashMap<>();r.put("name",n);r.put("ownerUid",user.getUid());r.put("ownerName",safeName());r.put("private",false);r.put("createdAt",FieldValue.serverTimestamp());r.put("updatedAt",FieldValue.serverTimestamp());db.collection("live_rooms").add(r).addOnSuccessListener(ref->openRoom(ref.getId(),n,user.getUid())).addOnFailureListener(e->toast("Create failed"));});label("Live rooms",20,Color.WHITE,true);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);page.addView(list);roomsListener=db.collection("live_rooms").orderBy("createdAt",Query.Direction.DESCENDING).limit(30).addSnapshotListener((snap,error)->{if(error!=null||snap==null)return;list.removeAllViews();for(DocumentSnapshot doc:snap.getDocuments()){String n=doc.getString("name"),o=doc.getString("ownerUid"),on=doc.getString("ownerName");Boolean priv=doc.getBoolean("private");String ph=doc.getString("passwordHash");Button b=new Button(this);b.setAllCaps(false);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setText((Boolean.TRUE.equals(priv)?"🔒 ":ph!=null?"🔑 ":"")+(n==null?"Live room":n)+"\nHost: "+(on==null?"KING user":on));b.setOnClickListener(v->openRoom(doc.getId(),n==null?"Live room":n,o));list.addView(b,new LinearLayout.LayoutParams(-1,dp(68)));}});}
 private void openRoom(String roomId,String roomName,String ownerUid){clearListeners();openRoomId=roomId;base(roomName,"Live cloud room");button("‹ Back",CARD,v->renderRooms());button("🎛 Enter Seats, Mic & Host Controls",CARD,v->{Intent i=new Intent(this,RoomEntryActivity.class);i.putExtra("roomId",roomId);i.putExtra("roomName",roomName);i.putExtra("name",safeName());i.putExtra("ownerUid",ownerUid);startActivity(i);});button("🎤 Join REAL voice test",PURPLE,v->{Intent i=new Intent(this,VoiceWebActivity.class);i.putExtra("roomId",roomId);i.putExtra("roomName",roomName);startActivity(i);});label("Room chat",19,Color.WHITE,true);LinearLayout chat=new LinearLayout(this);chat.setOrientation(LinearLayout.VERTICAL);page.addView(chat);messagesListener=db.collection("live_rooms").document(roomId).collection("messages").orderBy("createdAt",Query.Direction.ASCENDING).limit(80).addSnapshotListener((snap,error)->{if(error!=null||snap==null)return;chat.removeAllViews();for(DocumentSnapshot d:snap.getDocuments()){TextView row=new TextView(this);row.setText((d.getString("senderName")==null?"User":d.getString("senderName"))+": "+(d.getString("text")==null?"":d.getString("text")));row.setTextColor(Color.WHITE);row.setPadding(dp(10),dp(8),dp(10),dp(8));chat.addView(row);}});EditText m=input("Message everyone");button("Send",PURPLE,v->{String text=m.getText().toString().trim();if(text.isEmpty()||text.length()>500)return;Map<String,Object>d=new HashMap<>();d.put("senderUid",user.getUid());d.put("senderName",safeName());d.put("text",text);d.put("createdAt",FieldValue.serverTimestamp());db.collection("live_rooms").document(roomId).collection("messages").add(d).addOnSuccessListener(x->m.setText(""));});}
 private String safeName(){String n=user.getDisplayName();if(n!=null&&!n.trim().isEmpty())return n.trim();String p=user.getPhoneNumber();if(p!=null&&p.length()>=4)return"KING "+p.substring(p.length()-4);return"KING User";} private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}@Override public void onBackPressed(){if(openRoomId!=null)renderRooms();else super.onBackPressed();}@Override protected void onDestroy(){clearListeners();super.onDestroy();}
}
