from pathlib import Path
import re
P=Path('app/src/main/java/com/kingplus/social/PartyActivity.java')
B=Path('app/build.gradle')
s=P.read_text(encoding='utf-8')

if 'import android.content.ClipData;' not in s:
    s=s.replace('import android.content.Intent;\n','import android.content.Intent;\nimport android.content.ClipData;\nimport android.content.ClipboardManager;\n',1)

s=s.replace('ScrollView scroll=new ScrollView(this);\n        LinearLayout root=', 'ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setVerticalScrollBarEnabled(false);\n        LinearLayout root=',1)
s=s.replace('root.setPadding(dp(18),dp(12),dp(18),dp(16));', 'root.setPadding(dp(18),dp(10),dp(18),dp(28));',1)
s=s.replace('LinearLayout.LayoutParams afp=new LinearLayout.LayoutParams(dp(104),dp(104));','LinearLayout.LayoutParams afp=new LinearLayout.LayoutParams(dp(96),dp(96));',1)
s=s.replace('dialog.setOnShowListener(x->{android.view.Window w=dialog.getWindow();if(w!=null){w.setLayout(-1,-2);w.setGravity(Gravity.BOTTOM);}});','dialog.setOnShowListener(x->{android.view.Window w=dialog.getWindow();if(w!=null){w.setLayout(-1,(int)(getResources().getDisplayMetrics().heightPixels*.92f));w.setGravity(Gravity.BOTTOM);}});',1)

s=s.replace('family.addView(famIcon,new LinearLayout.LayoutParams(dp(48),dp(48)));','family.addView(famIcon,new LinearLayout.LayoutParams(dp(48),dp(56)));',1)
s=s.replace('family.addView(famInfo,new LinearLayout.LayoutParams(0,dp(48),1));','famInfo.setGravity(Gravity.CENTER_VERTICAL);family.addView(famInfo,new LinearLayout.LayoutParams(0,dp(56),1));',1)
s=s.replace('family.addView(famArrow,new LinearLayout.LayoutParams(dp(36),dp(48)));LinearLayout.LayoutParams fmp=new LinearLayout.LayoutParams(-1,dp(68));','family.addView(famArrow,new LinearLayout.LayoutParams(dp(36),dp(56)));family.setOnClickListener(v->profileFamilyDialog(uid,fallbackName));LinearLayout.LayoutParams fmp=new LinearLayout.LayoutParams(-1,dp(78));',1)
s=s.replace('relation.addView(relIcon,new LinearLayout.LayoutParams(dp(56),dp(48)));','relation.addView(relIcon,new LinearLayout.LayoutParams(dp(56),dp(56)));',1)
s=s.replace('relation.addView(relInfo,new LinearLayout.LayoutParams(0,dp(48),1));','relInfo.setGravity(Gravity.CENTER_VERTICAL);relation.addView(relInfo,new LinearLayout.LayoutParams(0,dp(56),1));',1)
s=s.replace('relation.addView(relBadge,new LinearLayout.LayoutParams(dp(44),dp(48)));LinearLayout.LayoutParams rlp=new LinearLayout.LayoutParams(-1,dp(68));','relation.addView(relBadge,new LinearLayout.LayoutParams(dp(44),dp(56)));relation.setOnClickListener(v->profileRelationshipDialog(uid,fallbackName));LinearLayout.LayoutParams rlp=new LinearLayout.LayoutParams(-1,dp(78));',1)

s=s.replace('LinearLayout wallRow=profileInfoRow("Gift Wall","No gifts yet","🎁   🌹   💗   ›");root.addView(wallRow,new LinearLayout.LayoutParams(-1,dp(62)));','LinearLayout wallRow=profileInfoRow("Gift Wall","Tap to view real room gifts","🎁   🌹   💗   ›");wallRow.setOnClickListener(v->profileGiftWallDialog(uid,fallbackName));root.addView(wallRow,new LinearLayout.LayoutParams(-1,dp(68)));',1)
s=s.replace('LinearLayout medalsRow=profileInfoRow("Medals","No medals yet","🏅   🥇   👑   ›");root.addView(medalsRow,new LinearLayout.LayoutParams(-1,dp(62)));','LinearLayout medalsRow=profileInfoRow("Medals","Tap to view achievements","🏅   🥇   👑   ›");medalsRow.setOnClickListener(v->profileMedalsDialog(uid,fallbackName,host));root.addView(medalsRow,new LinearLayout.LayoutParams(-1,dp(68)));',1)
s=s.replace('identity.setGravity(Gravity.CENTER);root.addView(identity,new LinearLayout.LayoutParams(-1,dp(34)));','identity.setGravity(Gravity.CENTER);identity.setOnClickListener(v->copyKingId(uid));root.addView(identity,new LinearLayout.LayoutParams(-1,dp(36)));',1)

old='''        LinearLayout cards=new LinearLayout(this);cards.setGravity(Gravity.CENTER);\n        String[] cs={"⭐  VIP level\\n—","🏆  Contribution\\n—","🔥  Charisma\\n—"};int[] cc={0xffe6f8ff,0xffe9fff6,0xfffff7d9};\n        for(int i=0;i<cs.length;i++){TextView x=tv(cs[i],11,0xff395065,true);x.setGravity(Gravity.CENTER);x.setBackground(bg(cc[i],10));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(70),1);cp.setMargins(dp(3),dp(8),dp(3),dp(8));cards.addView(x,cp);}root.addView(cards,new LinearLayout.LayoutParams(-1,dp(86)));'''
new='''        LinearLayout cards=new LinearLayout(this);cards.setGravity(Gravity.CENTER);\n        TextView vipStat=profileStatCard("⭐  VIP level","vip.0",0xffe6f8ff);TextView contributionStat=profileStatCard("🏆  Contribution","0",0xffe9fff6);TextView charismaStat=profileStatCard("🔥  Charisma","0",0xfffff7d9);\n        for(TextView x:new TextView[]{vipStat,contributionStat,charismaStat}){LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(72),1);cp.setMargins(dp(3),dp(7),dp(3),dp(7));cards.addView(x,cp);}root.addView(cards,new LinearLayout.LayoutParams(-1,dp(86)));\n        contributionStat.setOnClickListener(v->profileGiftWallDialog(uid,fallbackName));charismaStat.setOnClickListener(v->profileGiftWallDialog(uid,fallbackName));'''
if old not in s: raise SystemExit('stats template changed')
s=s.replace(old,new,1)

needle='''            db.collection("public_profiles").document(uid).get().addOnSuccessListener(p->{if(p.exists()){String pn=p.getString("displayName");if(pn!=null&&!pn.trim().isEmpty())n.setText((host?"👑 ":"")+pn.trim());Long lv=p.getLong("level");if(lv!=null)level.setText("Lv "+Math.max(1,lv));Long vv=p.getLong("vipLevel");if(vv!=null)vip.setText("💎 VIP "+Math.max(0,vv));}});'''
repl=needle+'\n            loadProfileRoomStats(uid,vip,level,vipStat,contributionStat,charismaStat);'
if needle not in s: raise SystemExit('public profile template changed')
s=s.replace(needle,repl,1)

s=s.replace('row.setPadding(dp(10),dp(5),dp(8),dp(5));','row.setPadding(dp(10),dp(7),dp(8),dp(7));',1)
s=s.replace('row.addView(info,new LinearLayout.LayoutParams(0,dp(52),1));','info.setGravity(Gravity.CENTER_VERTICAL);row.addView(info,new LinearLayout.LayoutParams(0,dp(56),1));',1)
s=s.replace('row.addView(r,new LinearLayout.LayoutParams(dp(185),dp(52)));return row;','row.addView(r,new LinearLayout.LayoutParams(dp(185),dp(56)));return row;',1)
s=s.replace('    private void toggleSeatQueue(){\n        if(cloudRoom&&db!=null){','    private void toggleSeatQueue(){\n        if(!isModerator()){toast("Host/co-host controls the seat queue");return;}\n        if(cloudRoom&&db!=null){',1)

insert=s.index('    private String publicId(')
helpers=r'''    private TextView profileStatCard(String title,String value,int color){TextView t=tv(title+"\n"+value,11,0xff395065,true);t.setGravity(Gravity.CENTER);t.setBackground(bg(color,10));return t;}
    private String compactNumber(long value){if(value>=1000000L)return String.format(java.util.Locale.US,"%.1fM",value/1000000.0);if(value>=1000L)return String.format(java.util.Locale.US,"%.1fK",value/1000.0);return String.valueOf(Math.max(0L,value));}
    private void copyKingId(String uid){String value=publicId(uid);ClipboardManager cm=(ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm!=null)cm.setPrimaryClip(ClipData.newPlainText("KING ID",value));toast("KING ID copied: "+value);}
    private void loadProfileRoomStats(String uid,TextView vip,TextView level,TextView vipStat,TextView contributionStat,TextView charismaStat){
        if(db==null||roomId==null||uid==null)return;db.collection("live_rooms").document(roomId).collection("events").orderBy("createdAt",Query.Direction.DESCENDING).limit(100).get().addOnSuccessListener(q->{long sent=0,received=0,activity=0;for(DocumentSnapshot d:q.getDocuments()){String a=d.getString("actorUid"),t=d.getString("targetUid"),type=d.getString("type");Long raw=d.getLong("giftValue");long v=raw==null?0:Math.max(0,raw);if(uid.equals(a)){activity++;if("gift".equals(type))sent+=v;}if(uid.equals(t)&&"gift".equals(type))received+=v;}int v=(int)Math.min(12,sent/10000),lv=(int)Math.min(99,1+activity/10+(sent+received)/50000);vip.setText("💎 VIP "+v);level.setText("Lv "+Math.max(1,lv));vipStat.setText("⭐  VIP level\nvip."+v);contributionStat.setText("🏆  Contribution\n"+compactNumber(sent));charismaStat.setText("🔥  Charisma\n"+compactNumber(received));});
    }
    private void profileFamilyDialog(String uid,String name){boolean self=user!=null&&uid.equals(user.getUid());if(self){SharedPreferences p=getSharedPreferences("MainActivity",MODE_PRIVATE);String family=p.getString("family_name","Not joined"),code=p.getString("family_code","");new AlertDialog.Builder(this).setTitle("👑 Family").setMessage("Current family: "+family+(code.isEmpty()?"":"\nFamily code: "+code)).setPositiveButton("Open Me page",(d,w)->{Intent i=new Intent(this,MainActivity.class);i.putExtra("openTab",4);startActivity(i);}).setNeutralButton("Share Family",(d,w)->shareFamilyRoom()).setNegativeButton("Close",null).show();}else new AlertDialog.Builder(this).setTitle("👑 "+name+" • Family").setMessage("Family details stay private until shared. You can invite this user in private chat or share your Family room.").setPositiveButton("Private chat",(d,w)->openPrivateChat(uid,name)).setNeutralButton("Share Family",(d,w)->shareFamilyRoom()).setNegativeButton("Close",null).show();}
    private void profileRelationshipDialog(String uid,String name){if(user!=null&&uid.equals(user.getUid())){new AlertDialog.Builder(this).setTitle("💞 Relationship").setMessage("Manage your relationship from the Me page.").setPositiveButton("Open Me page",(d,w)->{Intent i=new Intent(this,MainActivity.class);i.putExtra("openTab",4);startActivity(i);}).setNegativeButton("Close",null).show();return;}new AlertDialog.Builder(this).setTitle("💞 "+name).setMessage("Start a private chat or send a relationship gift.").setPositiveButton("Private chat",(d,w)->openPrivateChat(uid,name)).setNeutralButton("Send Gift",(d,w)->giftDialogFor(uid,name)).setNegativeButton("Close",null).show();}
    private void profileGiftWallDialog(String uid,String name){if(db==null||roomId==null){toast("Live room required");return;}db.collection("live_rooms").document(roomId).collection("events").orderBy("createdAt",Query.Direction.DESCENDING).limit(100).get().addOnSuccessListener(q->{ArrayList<String> rows=new ArrayList<>();long total=0;for(DocumentSnapshot d:q.getDocuments())if("gift".equals(d.getString("type"))&&uid.equals(d.getString("targetUid"))){String g=d.getString("giftName"),a=d.getString("actorName");Long val=d.getLong("giftValue"),qty=d.getLong("giftQty");long v=val==null?0:val;total+=v;rows.add((g==null?"Gift":g)+" x"+(qty==null?1:qty)+" • from "+(a==null?"User":a)+" • 💎"+v);}if(rows.isEmpty()){new AlertDialog.Builder(this).setTitle("🎁 "+name+" • Gift Wall").setMessage("No gifts received in this room yet.").setPositiveButton("Send first gift",(d,w)->giftDialogFor(uid,name)).setNegativeButton("Close",null).show();return;}new AlertDialog.Builder(this).setTitle("🎁 Gift Wall • Total 💎"+compactNumber(total)).setItems(rows.toArray(new String[0]),null).setPositiveButton("Send Gift",(d,w)->giftDialogFor(uid,name)).setNegativeButton("Close",null).show();}).addOnFailureListener(e->toast("Gift Wall unavailable: "+msg(e)));}
    private void profileMedalsDialog(String uid,String name,boolean host){if(db==null||roomId==null){toast("Live room required");return;}db.collection("live_rooms").document(roomId).collection("events").orderBy("createdAt",Query.Direction.DESCENDING).limit(100).get().addOnSuccessListener(q->{long sent=0,received=0,activity=0;for(DocumentSnapshot d:q.getDocuments()){Long val=d.getLong("giftValue");if(uid.equals(d.getString("actorUid"))){activity++;if("gift".equals(d.getString("type"))&&val!=null)sent+=val;}if(uid.equals(d.getString("targetUid"))&&"gift".equals(d.getString("type"))&&val!=null)received+=val;}ArrayList<String> m=new ArrayList<>();if(host)m.add("👑 Room Host");if(activity>=5)m.add("🏅 Active Member");if(sent>0)m.add("💎 Supporter • "+compactNumber(sent));if(received>0)m.add("🌟 Gift Star • "+compactNumber(received));if(m.isEmpty())m.add("No medals earned in this room yet");new AlertDialog.Builder(this).setTitle("🏅 "+name+" • Medals").setItems(m.toArray(new String[0]),null).setPositiveButton("OK",null).show();}).addOnFailureListener(e->toast("Medals unavailable: "+msg(e)));}

'''
s=s[:insert]+helpers+s[insert:]

P.write_text(s,encoding='utf-8')
b=B.read_text(encoding='utf-8');b=re.sub(r"versionCode\s+\d+;\s+versionName\s+'[^']+'","versionCode 67; versionName '4.4.1'",b);B.write_text(b,encoding='utf-8')
Path('CHANGELOG-v4.4.1.txt').write_text('KING Plus v4.4.1 — Party Profile Fit + Working Actions\n\nFixes the clipped room profile sheet with a 92% screen-height scrollable layout. Family, Relationship, Gift Wall, Medals and KING ID are now interactive. Contribution/Charisma/VIP progress use real current-room gift/event data. Existing Play Center, Tools, host/co-host, seats, queue, music, private chat, gifts and moderation remain available. No-billing and TEST OTP 123456 remain unchanged.\n',encoding='utf-8')
print('Prepared v4.4.1')
