from pathlib import Path
import re

p = Path('app/src/main/java/com/kingplus/social/MainActivity.java')
s = p.read_text(encoding='utf-8')

old = '        rooms.add("Music & Friends"); rooms.add("KING Lounge"); rooms.add("Game Talk");\n'
if old not in s:
    raise SystemExit('v5.2: demo room seed line not found')
s = s.replace(old, '        // v5.2: do not seed fake/demo rooms. Real Party rooms come from Firebase.\n', 1)

rank_pattern = re.compile(r'''    private void rankingsPage\(\)\{.*?\n    \}\n    private void vipPage\(\)\{''', re.S)
rank_repl = '''    private void rankingsPage(){
        screen="rankings"; base("Rankings","Real KING Plus activity only");
        text("👑 Live rankings",20,Color.WHITE,true);
        if(firebaseAuth==null || firebaseAuth.getCurrentUser()==null || firestore==null){
            text("Sign in to view real community and room activity. KING Plus no longer shows sample leaderboard names.",14,MUTED,false);
            button("Sign in",PURPLE,this::login);
            button("Back to Profile",CARD,this::profile);
            return;
        }
        text("Sample users and made-up charm/coin totals have been removed.",14,MUTED,false);
        text("Open Party to view the real Room Ranking, Gift Senders, Gift History and live room activity generated by signed-in members.",14,Color.WHITE,false);
        button("🎤 Open real Party rankings",PURPLE,this::openPartyActivity);
        button("👥 Open real Followers / Friends",CARD,()->startActivity(new Intent(this,SocialActivity.class)));
        button("Back to Profile",CARD,this::profile);
    }
    private void vipPage(){'''
s, n = rank_pattern.subn(rank_repl, s, count=1)
if n != 1:
    raise SystemExit(f'v5.2: rankingsPage replace count={n}')

family_pattern = re.compile(r'''    private void familyAgencyPage\(\)\{.*?\n    \}\n\n    private void dailyCheckInPage\(\)\{''', re.S)
family_repl = '''    private void familyAgencyPage(){
        screen="family_agency"; base("Family & Agency","Verified account data only");
        text("🏠 Family & Agency",24,Color.WHITE,true);
        text("The old device-only sample family members, fake host counts and fake active-room counts have been removed.",14,MUTED,false);
        if(firebaseAuth==null || firebaseAuth.getCurrentUser()==null || firestore==null){
            text("Sign in with Google/Firebase first. Family/agency membership will only be shown when it is backed by a real account record.",14,Color.WHITE,false);
            button("Sign in",PURPLE,this::login);
        } else {
            text("Signed in as: "+displayName,15,Color.WHITE,true);
            text("No verified Family/Agency record is available for this account yet.",14,MUTED,false);
            button("🎤 Open Party",PURPLE,this::openPartyActivity);
        }
        button("Back to Profile",CARD,this::profile);
    }

    private void dailyCheckInPage(){'''
s, n = family_pattern.subn(family_repl, s, count=1)
if n != 1:
    raise SystemExit(f'v5.2: familyAgencyPage replace count={n}')

people_pattern = re.compile(r'''    private void peoplePage\(String title\)\{.*?\n    \}\n\n    private void userProfile\(String who\)\{''', re.S)
people_repl = '''    private void peoplePage(String title){
        // Use the Firebase-backed social screen instead of seeding fake people.
        startActivity(new Intent(this,SocialActivity.class));
    }

    private void userProfile(String who){'''
s, n = people_pattern.subn(people_repl, s, count=1)
if n != 1:
    raise SystemExit(f'v5.2: peoplePage replace count={n}')

notif_pattern = re.compile(r'''    private void notificationsCenter\(\)\{.*?\n    \}\n\n    private void searchCommunity\(\)\{''', re.S)
notif_repl = '''    private void notificationsCenter(){
        screen="notifications"; base("Notifications","Real activity from your KING Plus account");
        String raw=getPreferences(0).getString("notifications_log","");
        if(raw.isEmpty()) {
            text("No notifications yet.",16,Color.WHITE,true);
            text("KING Plus no longer inserts sample follows, gifts, invites or live-room notifications.",13,MUTED,false);
        } else {
            for(String n:raw.split("[|][|][|]")) if(!n.trim().isEmpty()) button(n,CARD,()->Toast.makeText(this,"Opened",Toast.LENGTH_SHORT).show());
        }
        button("🔔 Enable / refresh push notifications",PURPLE,()->{PushNotifications.requestPermission(this);PushNotifications.refreshToken();Toast.makeText(this,"Push notification setup refreshed",Toast.LENGTH_SHORT).show();});
        button("Mark all as read",CARD,()->{getPreferences(0).edit().putBoolean("notifications_read",true).apply();Toast.makeText(this,"All notifications marked as read",Toast.LENGTH_SHORT).show();});
        if(!raw.isEmpty()) button("Clear notifications",CARD,()->{getPreferences(0).edit().putString("notifications_log","").apply();notificationsCenter();});
        button("Back to Messages",CARD,this::messages);
    }

    private void searchCommunity(){'''
s, n = notif_pattern.subn(notif_repl, s, count=1)
if n != 1:
    raise SystemExit(f'v5.2: notificationsCenter replace count={n}')

search_pattern = re.compile(r'''    private void searchCommunity\(\)\{.*?\n    \}\n\n    private void createRoomDialog\(\)\{.*?\n    \}\n''', re.S)
search_repl = '''    private void searchCommunity(){
        startActivity(new Intent(this,SocialActivity.class));
    }

    private void createRoomDialog(){
        // Legacy local preview creation is disabled. The real Party screen creates Firebase rooms.
        openPartyActivity();
    }
'''
s, n = search_pattern.subn(search_repl, s, count=1)
if n != 1:
    raise SystemExit(f'v5.2: legacy search/create replace count={n}')

# If the old home renderer is ever called by stale navigation, route straight to the real Party screen.
render_pattern = re.compile(r'''    private void renderHome\(String category\) \{.*?\n    \}\n    private String\[\]\[\] roomData\(String category\)\{''', re.S)
render_repl = '''    private void renderHome(String category) {
        openPartyActivity();
    }
    private String[][] roomData(String category){'''
s, n = render_pattern.subn(render_repl, s, count=1)
if n != 1:
    raise SystemExit(f'v5.2: renderHome replace count={n}')

p.write_text(s, encoding='utf-8')
print('v5.2 real-data cleanup applied')
