package com.kingplus.social;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputFilter;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.google.firebase.Timestamp;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.ListenerRegistration;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Realtime 2/4-player Ludo backed by /ludo_matches/{code}. */
public class OnlineLudoActivity extends Activity {
    private static final int BG=0xff151126, CARD=0xff2b2040, CARD2=0xff382951,
            PURPLE=0xff8a49ed, GOLD=0xffffd768, MUTED=0xffcfc4df, GREEN=0xff39cf8e;
    private static final String CODE_CHARS="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
    private FirebaseFirestore db; private FirebaseUser me; private ListenerRegistration listener;
    private String code=""; private Map<String,Object> state;
    private LinearLayout page,lobbyBox,playersBox,piecesBox,actionsBox;
    private TextView statusText,codeText,turnText; private EditText codeInput;
    private final SecureRandom random=new SecureRandom();

    @Override public void onCreate(Bundle b){super.onCreate(b);try{db=FirebaseFirestore.getInstance();me=FirebaseAuth.getInstance().getCurrentUser();}catch(Exception e){db=null;me=null;}build();if(db==null||me==null){status("Sign in with Google / phone first to play Online Ludo.",0xffffa6a6);setLobbyEnabled(false);return;}String incoming=cleanCode(getIntent().getStringExtra("ludoCode"));if(!incoming.isEmpty()){codeInput.setText(incoming);joinMatch(incoming);}}
    @Override protected void onDestroy(){if(listener!=null)listener.remove();super.onDestroy();}
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);} private String s(Object x){return x==null?"":String.valueOf(x).trim();}
    private GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private TextView tv(String text,int size,int color,boolean bold){TextView v=new TextView(this);v.setText(text);v.setTextSize(size);v.setTextColor(color);if(bold)v.setTypeface(null,Typeface.BOLD);v.setPadding(dp(10),dp(8),dp(10),dp(8));return v;}
    private Button btn(String text){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(14);b.setBackground(bg(PURPLE,14));return b;}
    private void toast(String x){Toast.makeText(this,x,Toast.LENGTH_SHORT).show();} private void status(String x,int color){statusText.setText(x);statusText.setTextColor(color);}

    private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);ScrollView sc=new ScrollView(this);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(14),dp(8),dp(14),dp(30));sc.addView(page);root.addView(sc,new LinearLayout.LayoutParams(-1,-1));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=tv("‹",34,Color.WHITE,true);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(48),dp(54)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.addView(tv("🎲 KING Online Ludo",23,Color.WHITE,true));titles.addView(tv("2 or 4 real players • realtime Firebase match",12,MUTED,false));head.addView(titles,new LinearLayout.LayoutParams(0,dp(64),1));page.addView(head);
        statusText=tv("Create a room or join with a 6-character code",15,GOLD,true);statusText.setGravity(Gravity.CENTER);statusText.setBackground(bg(CARD,16));LinearLayout.LayoutParams st=new LinearLayout.LayoutParams(-1,-2);st.setMargins(0,dp(6),0,dp(10));page.addView(statusText,st);
        lobbyBox=new LinearLayout(this);lobbyBox.setOrientation(LinearLayout.VERTICAL);lobbyBox.setPadding(dp(12),dp(12),dp(12),dp(12));lobbyBox.setBackground(bg(CARD,18));codeInput=new EditText(this);codeInput.setHint("Room code e.g. ABC234");codeInput.setHintTextColor(0xff9d91b1);codeInput.setTextColor(Color.WHITE);codeInput.setSingleLine(true);codeInput.setFilters(new InputFilter[]{new InputFilter.LengthFilter(6)});codeInput.setBackground(bg(CARD2,12));codeInput.setPadding(dp(14),0,dp(14),0);lobbyBox.addView(codeInput,new LinearLayout.LayoutParams(-1,dp(50)));LinearLayout row=new LinearLayout(this);row.setPadding(0,dp(8),0,0);Button c2=btn("Create 1 vs 1");c2.setOnClickListener(v->createMatch(2));Button c4=btn("Create 4 Player");c4.setOnClickListener(v->createMatch(4));row.addView(c2,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout.LayoutParams c4lp=new LinearLayout.LayoutParams(0,dp(50),1);c4lp.setMargins(dp(6),0,0,0);row.addView(c4,c4lp);lobbyBox.addView(row);Button join=btn("Join Room Code");join.setOnClickListener(v->joinMatch(cleanCode(codeInput.getText().toString())));LinearLayout.LayoutParams jp=new LinearLayout.LayoutParams(-1,dp(50));jp.setMargins(0,dp(7),0,0);lobbyBox.addView(join,jp);page.addView(lobbyBox,new LinearLayout.LayoutParams(-1,-2));
        LinearLayout matchHead=new LinearLayout(this);matchHead.setGravity(Gravity.CENTER_VERTICAL);codeText=tv("Room —",17,GOLD,true);matchHead.addView(codeText,new LinearLayout.LayoutParams(0,dp(50),1));Button share=btn("Share");share.setOnClickListener(v->shareCode());matchHead.addView(share,new LinearLayout.LayoutParams(dp(92),dp(44)));LinearLayout.LayoutParams mhp=new LinearLayout.LayoutParams(-1,dp(54));mhp.setMargins(0,dp(10),0,0);page.addView(matchHead,mhp);turnText=tv("Waiting for match",14,MUTED,true);turnText.setGravity(Gravity.CENTER);page.addView(turnText,new LinearLayout.LayoutParams(-1,dp(46)));playersBox=new LinearLayout(this);playersBox.setOrientation(LinearLayout.VERTICAL);page.addView(playersBox,new LinearLayout.LayoutParams(-1,-2));piecesBox=new LinearLayout(this);piecesBox.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams pbp=new LinearLayout.LayoutParams(-1,-2);pbp.setMargins(0,dp(8),0,0);page.addView(piecesBox,pbp);actionsBox=new LinearLayout(this);actionsBox.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams abp=new LinearLayout.LayoutParams(-1,-2);abp.setMargins(0,dp(10),0,0);page.addView(actionsBox,abp);setSafe(root);setContentView(root);render();}
    private void setSafe(View root){ViewCompat.setOnApplyWindowInsetsListener(root,(v,in)->{Insets z=in.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(z.left,z.top,z.right,z.bottom);return in;});ViewCompat.requestApplyInsets(root);}
    private void setLobbyEnabled(boolean yes){for(int i=0;i<lobbyBox.getChildCount();i++)lobbyBox.getChildAt(i).setEnabled(yes);codeInput.setEnabled(yes);} private String cleanCode(String x){if(x==null)return "";return x.toUpperCase(Locale.US).replaceAll("[^A-Z2-9]","").trim();}
    private String newCode(){StringBuilder b=new StringBuilder();for(int i=0;i<6;i++)b.append(CODE_CHARS.charAt(random.nextInt(CODE_CHARS.length())));return b.toString();}
    private String name(){String n=me==null?"":s(me.getDisplayName());if(n.isEmpty()&&me!=null&&!s(me.getEmail()).isEmpty())n=s(me.getEmail()).split("@")[0];if(n.isEmpty())n="KING Player";if(n.length()>80)n=n.substring(0,80);return n;} private DocumentReference ref(){return db.collection("ludo_matches").document(code);}

    private void createMatch(int capacity){if(me==null)return;status("Creating secure online match…",GOLD);createTry(capacity,0);} private void createTry(int capacity,int tries){if(tries>5){status("Could not create room. Try again.",0xffffa6a6);return;}String c=newCode();DocumentReference r=db.collection("ludo_matches").document(c);db.runTransaction(tx->{DocumentSnapshot d=tx.get(r);if(d.exists())throw new IllegalStateException("code collision");tx.set(r,fresh(c,capacity));return null;}).addOnSuccessListener(v->{open(c);toast("Room created • "+c);}).addOnFailureListener(e->{if(String.valueOf(e.getMessage()).contains("collision"))createTry(capacity,tries+1);else showError("Create failed",e);});}
    private Map<String,Object> fresh(String c,int capacity){Map<String,Object> m=new HashMap<>();m.put("schema",1L);m.put("code",c);m.put("ownerUid",me.getUid());m.put("players",new ArrayList<>(Arrays.asList(me.getUid(),"","","")));m.put("names",new ArrayList<>(Arrays.asList(name(),"","","")));m.put("ready",new ArrayList<>(Arrays.asList(false,false,false,false)));m.put("capacity",(long)capacity);m.put("pieces",new ArrayList<>(Arrays.asList(-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L)));m.put("turn",0L);m.put("dice",0L);m.put("sixes",0L);m.put("winner",-1L);m.put("phase","lobby");m.put("revision",0L);m.put("action","create");m.put("actorUid",me.getUid());m.put("selected",-1L);m.put("updatedAt",FieldValue.serverTimestamp());m.put("rollAt",FieldValue.serverTimestamp());return m;}
    private void joinMatch(String c){if(c.length()!=6){toast("Enter a valid 6-character room code");return;}if(me==null)return;code=c;DocumentReference r=ref();status("Joining "+c+"…",GOLD);db.runTransaction(tx->{DocumentSnapshot d=tx.get(r);if(!d.exists())throw new IllegalStateException("Room not found");Map<String,Object> o=d.getData();if(o==null)throw new IllegalStateException("Room unavailable");List<String> ps=strList(o.get("players"));if(ps.contains(me.getUid()))return null;if(!"lobby".equals(s(o.get("phase"))))throw new IllegalStateException("Match already started");int cap=i(o.get("capacity"));int seat=-1;if(cap==2){if(ps.size()>2&&ps.get(2).isEmpty())seat=2;}else for(int x=1;x<4;x++)if(ps.get(x).isEmpty()){seat=x;break;}if(seat<0)throw new IllegalStateException("Room is full");List<String> names=strList(o.get("names"));List<Boolean> ready=boolList(o.get("ready"));ps.set(seat,me.getUid());names.set(seat,name());ready.set(seat,false);Map<String,Object> n=copy(o);n.put("players",ps);n.put("names",names);n.put("ready",ready);action(n,"join",seat);tx.set(r,n);return null;}).addOnSuccessListener(v->open(c)).addOnFailureListener(e->showError("Join failed",e));}
    private void open(String c){code=c;codeInput.setText(c);setLobbyEnabled(false);codeText.setText("Room  "+c);listen();}
    private void listen(){if(listener!=null)listener.remove();listener=ref().addSnapshotListener((d,e)->{if(e!=null){showError("Live match",e);return;}if(d==null||!d.exists()){state=null;status("Room closed",0xffffa6a6);render();setLobbyEnabled(true);return;}state=d.getData();render();if(state!=null&&"resolve".equals(s(state.get("phase")))&&me!=null&&strList(state.get("players")).contains(me.getUid()))resolveDice();});}

    private void render(){playersBox.removeAllViews();piecesBox.removeAllViews();actionsBox.removeAllViews();if(state==null){codeText.setText(code.isEmpty()?"Room —":"Room  "+code);turnText.setText("Create or join a room to start");return;}String phase=s(state.get("phase"));List<String> ps=strList(state.get("players"));List<String> ns=strList(state.get("names"));List<Boolean> ready=boolList(state.get("ready"));int cap=i(state.get("capacity")),turn=i(state.get("turn")),dice=i(state.get("dice")),winner=i(state.get("winner"));status("Online • "+(cap==2?"1 vs 1":"4 Players")+" • "+phase.toUpperCase(Locale.US),GREEN);codeText.setText("Room  "+code);if("finished".equals(phase)&&winner>=0&&winner<ns.size())turnText.setText("🏆 Winner: "+safeName(ns,winner));else if("cancelled".equals(phase))turnText.setText("Match cancelled • Host can start a rematch");else if("lobby".equals(phase))turnText.setText("Ready up • Host starts when all required players are ready");else turnText.setText("Turn: "+safeName(ns,turn)+(dice>0?"  •  Dice "+dice:"")+((turn<ps.size()&&me!=null&&me.getUid().equals(ps.get(turn)))?"  •  YOUR TURN":""));int[] colors={0xffff5b67,0xff4aa8ff,0xffffc646,0xff52cf76};String[] dots={"🔴","🔵","🟡","🟢"};List<Long> pieceList=longList(state.get("pieces"));for(int seat=0;seat<4;seat++){if(cap==2&&(seat==1||seat==3))continue;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setBackground(bg(CARD,14));TextView p=tv(dots[seat]+"  "+(ps.get(seat).isEmpty()?"Waiting…":safeName(ns,seat)),14,Color.WHITE,true);row.addView(p,new LinearLayout.LayoutParams(0,dp(48),1));TextView badge=tv(ps.get(seat).isEmpty()?"":(ready.get(seat)?"READY":"NOT READY"),11,ready.get(seat)?GREEN:MUTED,true);badge.setGravity(Gravity.CENTER);row.addView(badge,new LinearLayout.LayoutParams(dp(92),dp(48)));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(50));rp.setMargins(0,dp(3),0,dp(3));playersBox.addView(row,rp);LinearLayout pcs=new LinearLayout(this);pcs.setGravity(Gravity.CENTER);for(int k=0;k<4;k++){int idx=seat*4+k;long pos=idx<pieceList.size()?pieceList.get(idx):-1;Button q=btn(pieceLabel(k,pos));q.setTextSize(11);q.setBackground(bg(colors[seat],12));final int piece=k;q.setEnabled(canMove(seat,piece));q.setAlpha(q.isEnabled()?1f:.75f);q.setOnClickListener(v->movePiece(piece));LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(0,dp(48),1);qp.setMargins(dp(2),0,dp(2),0);pcs.addView(q,qp);}LinearLayout.LayoutParams pcsp=new LinearLayout.LayoutParams(-1,dp(52));pcsp.setMargins(0,0,0,dp(4));piecesBox.addView(pcs,pcsp);}buildActions(phase,ps,ready,cap,turn);}
    private String safeName(List<String> ns,int i){if(i<0||i>=ns.size()||s(ns.get(i)).isEmpty())return "Player "+(i+1);return s(ns.get(i));} private String pieceLabel(int k,long pos){if(pos<0)return "P"+(k+1)+" • Yard";if(pos>=56)return "P"+(k+1)+" • HOME";return "P"+(k+1)+" • "+pos+"/56";}
    private void buildActions(String phase,List<String> ps,List<Boolean> ready,int cap,int turn){if(me==null)return;int seat=ps.indexOf(me.getUid());boolean owner=me.getUid().equals(s(state.get("ownerUid")));if("lobby".equals(phase)){if(seat>=0){Button readyBtn=btn(ready.get(seat)?"✅ Ready • tap to undo":"✅ I am Ready");readyBtn.setOnClickListener(v->toggleReady());actionsBox.addView(readyBtn,new LinearLayout.LayoutParams(-1,dp(50)));}if(owner){Button start=btn("▶ Start Match");start.setEnabled(canStart(ps,ready,cap));start.setOnClickListener(v->startMatch());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50));lp.setMargins(0,dp(6),0,0);actionsBox.addView(start,lp);}Button leave=btn(owner&&activePlayers(ps)==1?"Close Room":"Leave Room");leave.setOnClickListener(v->leaveLobby());LinearLayout.LayoutParams lp2=new LinearLayout.LayoutParams(-1,dp(48));lp2.setMargins(0,dp(6),0,0);actionsBox.addView(leave,lp2);}else if("roll".equals(phase)&&seat==turn){Button roll=btn("🎲 ROLL DICE");roll.setTextSize(18);roll.setOnClickListener(v->rollDice());actionsBox.addView(roll,new LinearLayout.LayoutParams(-1,dp(58)));}else if("move".equals(phase)&&seat==turn){TextView h=tv("Choose one highlighted piece above to move.",14,GOLD,true);h.setGravity(Gravity.CENTER);actionsBox.addView(h,new LinearLayout.LayoutParams(-1,dp(50)));}if(("roll".equals(phase)||"resolve".equals(phase)||"move".equals(phase))&&owner){Button cancel=btn("End Match");cancel.setOnClickListener(v->confirmCancel());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(46));lp.setMargins(0,dp(8),0,0);actionsBox.addView(cancel,lp);}if(("finished".equals(phase)||"cancelled".equals(phase))&&owner){Button rematch=btn("↻ Rematch");rematch.setOnClickListener(v->rematch());actionsBox.addView(rematch,new LinearLayout.LayoutParams(-1,dp(52)));}}
    private boolean canStart(List<String> ps,List<Boolean> rd,int cap){if(ps.get(0).isEmpty()||ps.get(2).isEmpty()||!rd.get(0)||!rd.get(2))return false;return cap==2||(!ps.get(1).isEmpty()&&!ps.get(3).isEmpty()&&rd.get(1)&&rd.get(3));} private int activePlayers(List<String> ps){int n=0;for(String x:ps)if(!s(x).isEmpty())n++;return n;}
    private boolean canMove(int seat,int piece){if(state==null||me==null||!"move".equals(s(state.get("phase"))))return false;List<String> ps=strList(state.get("players"));int turn=i(state.get("turn"));if(seat!=turn||turn>=ps.size()||!me.getUid().equals(ps.get(turn)))return false;List<Long> p=longList(state.get("pieces"));long pos=p.get(turn*4+piece);int d=i(state.get("dice"));return pos<0?d==6:pos<56&&pos+d<=56;}
    private void toggleReady(){transaction("ready",o->{List<String> ps=strList(o.get("players"));int seat=ps.indexOf(me.getUid());if(seat<0)throw new IllegalStateException("You are not in this room");List<Boolean> rd=boolList(o.get("ready"));rd.set(seat,!rd.get(seat));o.put("ready",rd);action(o,"ready",seat);});} private void startMatch(){transaction("start",o->{o.put("phase","roll");action(o,"start",-1);});}
    private void rollDice(){transaction("roll",o->{if(!"roll".equals(s(o.get("phase"))))throw new IllegalStateException("Not ready to roll");int t=i(o.get("turn"));List<String> ps=strList(o.get("players"));if(t<0||t>=ps.size()||!me.getUid().equals(ps.get(t)))throw new IllegalStateException("Wait for your turn");o.put("phase","resolve");o.put("dice",0L);o.put("rollAt",FieldValue.serverTimestamp());action(o,"roll",-1);}).addOnSuccessListener(v->ref().get().addOnSuccessListener(d->resolveDice()));}
    private void resolveDice(){if(state==null||!"resolve".equals(s(state.get("phase"))))return;db.runTransaction(tx->{DocumentSnapshot d=tx.get(ref());if(!d.exists())return null;Map<String,Object> o=copy(d.getData());if(!"resolve".equals(s(o.get("phase"))))return null;Timestamp ts=d.getTimestamp("rollAt");if(ts==null)return null;int die=(int)(ts.toDate().getTime()%6)+1,turn=i(o.get("turn")),sixes=i(o.get("sixes")),cap=i(o.get("capacity"));List<Long> pieces=longList(o.get("pieces"));boolean third=sixes==2&&die==6,can=!third&&anyMove(pieces,turn,die),pass=third||(!can&&die!=6);o.put("dice",(long)die);o.put("turn",(long)(pass?nextTurn(turn,cap):turn));o.put("sixes",(long)(pass?0:(die==6?sixes+1:0)));o.put("phase",can?"move":"roll");action(o,"resolve",-1);tx.set(ref(),o);return null;}).addOnFailureListener(e->{String msg=s(e.getMessage());if(!msg.toLowerCase(Locale.US).contains("permission"))toast("Dice sync: "+msg);});}
    private boolean anyMove(List<Long> p,int turn,int d){for(int k=0;k<4;k++){long x=p.get(turn*4+k);if(x<0?d==6:(x<56&&x+d<=56))return true;}return false;} private int nextTurn(int turn,int cap){return cap==2?(turn==0?2:0):(turn+1)%4;}
    private void movePiece(int chosen){transaction("move",o->{if(!"move".equals(s(o.get("phase"))))throw new IllegalStateException("Roll first");int turn=i(o.get("turn")),cap=i(o.get("capacity")),dice=i(o.get("dice"));List<String> ps=strList(o.get("players"));if(!me.getUid().equals(ps.get(turn)))throw new IllegalStateException("Wait for your turn");List<Long> before=longList(o.get("pieces"));List<Long> after=new ArrayList<>(before);int own=turn*4+chosen;long pos=before.get(own);if(!(pos<0?dice==6:(pos<56&&pos+dice<=56)))throw new IllegalStateException("That piece cannot move");long target=pos<0?0:pos+dice;after.set(own,target);int square=(int)((turn*13L+target)%52);boolean capture=target<=50&&(square%13!=0&&square%13!=8);if(capture){for(int c=0;c<4;c++)if(c!=turn)for(int k=0;k<4;k++){int ix=c*4+k;long q=before.get(ix);if(q>=0&&q<=50&&((c*13L+q)%52)==square)after.set(ix,-1L);}}boolean win=true;for(int k=0;k<4;k++)if(after.get(turn*4+k)!=56L){win=false;break;}boolean captured=countOnBoard(after)<countOnBoard(before),bonus=dice==6||target==56||captured;int nt=(win||bonus)?turn:nextTurn(turn,cap);o.put("pieces",after);o.put("turn",(long)nt);o.put("sixes",(long)(nt==turn?i(o.get("sixes")):0));o.put("winner",(long)(win?turn:-1));o.put("phase",win?"finished":"roll");action(o,"move",chosen);});} private int countOnBoard(List<Long> p){int n=0;for(Long x:p)if(x!=null&&x!=-1L)n++;return n;}
    private void leaveLobby(){if(state==null)return;List<String> ps=strList(state.get("players"));boolean owner=me.getUid().equals(s(state.get("ownerUid")));if(owner&&activePlayers(ps)==1){ref().delete().addOnSuccessListener(v->{state=null;code="";if(listener!=null)listener.remove();setLobbyEnabled(true);render();toast("Room closed");}).addOnFailureListener(e->showError("Close room",e));return;}transaction("leave",o->{List<String> p=strList(o.get("players"));List<String> ns=strList(o.get("names"));List<Boolean> rd=boolList(o.get("ready"));int seat=p.indexOf(me.getUid());if(seat<0)throw new IllegalStateException("Not in room");p.set(seat,"");ns.set(seat,"");rd.set(seat,false);o.put("players",p);o.put("names",ns);o.put("ready",rd);if(me.getUid().equals(s(o.get("ownerUid")))){String next="";for(String u:p)if(!u.isEmpty()){next=u;break;}o.put("ownerUid",next);}action(o,"leave",seat);}).addOnSuccessListener(v->{if(listener!=null)listener.remove();state=null;code="";setLobbyEnabled(true);render();});}
    private void confirmCancel(){new AlertDialog.Builder(this).setTitle("End Online Ludo?").setMessage("The current round will be cancelled for all players.").setPositiveButton("End",(d,w)->transaction("cancel",o->{o.put("phase","cancelled");action(o,"cancel",-1);})).setNegativeButton("Keep playing",null).show();}
    private void rematch(){transaction("rematch",o->{o.put("pieces",new ArrayList<>(Arrays.asList(-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L,-1L)));o.put("turn",0L);o.put("dice",0L);o.put("sixes",0L);o.put("winner",-1L);o.put("phase","lobby");o.put("ready",new ArrayList<>(Arrays.asList(false,false,false,false)));action(o,"rematch",-1);});}
    private interface Change{void apply(Map<String,Object> o);} private com.google.android.gms.tasks.Task<Void> transaction(String label,Change change){if(state==null)return com.google.android.gms.tasks.Tasks.forException(new IllegalStateException("No match"));return db.runTransaction(tx->{DocumentSnapshot d=tx.get(ref());if(!d.exists())throw new IllegalStateException("Room closed");Map<String,Object> o=copy(d.getData());change.apply(o);tx.set(ref(),o);return null;}).addOnFailureListener(e->showError(label,e));}
    private void action(Map<String,Object> o,String action,int selected){o.put("action",action);o.put("actorUid",me.getUid());o.put("selected",(long)selected);o.put("revision",(long)i(o.get("revision"))+1L);o.put("updatedAt",FieldValue.serverTimestamp());}
    private Map<String,Object> copy(Map<String,Object> in){return in==null?new HashMap<>():new HashMap<>(in);} @SuppressWarnings("unchecked") private List<String> strList(Object v){List<String> out=new ArrayList<>();if(v instanceof List)for(Object x:(List<Object>)v)out.add(s(x));while(out.size()<4)out.add("");return out;} @SuppressWarnings("unchecked") private List<Boolean> boolList(Object v){List<Boolean> out=new ArrayList<>();if(v instanceof List)for(Object x:(List<Object>)v)out.add(Boolean.TRUE.equals(x));while(out.size()<4)out.add(false);return out;} @SuppressWarnings("unchecked") private List<Long> longList(Object v){List<Long> out=new ArrayList<>();if(v instanceof List)for(Object x:(List<Object>)v)out.add(x instanceof Number?((Number)x).longValue():-1L);while(out.size()<16)out.add(-1L);return out;} private int i(Object v){return v instanceof Number?((Number)v).intValue():0;}
    private void shareCode(){if(code.isEmpty()){toast("Create or join a room first");return;}Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,"Join my KING Plus Online Ludo room: "+code);startActivity(Intent.createChooser(i,"Share Ludo code"));}
    private void showError(String where,Exception e){String msg=e==null?"Unknown error":s(e.getMessage());String low=msg.toLowerCase(Locale.US);if(low.contains("permission")||low.contains("denied"))status("Online Ludo server rules are not live yet • Firebase Rules permission required",0xffffa6a6);else status(where+": "+msg,0xffffa6a6);}
}
